#config_version=4
mode:
  start_events: both_ramps_made
  stop_events: ball_ending
  priority: 200

scoring:
  shot_rightramp:
    score: 50000
    block: true
  shot_leftramp:
    score: 50000
    block: true

slide_player:
  mode_both_ramps_made_started: slide_6
slides:
  slide_6:
  - type: text
    text: SHOOT RAMP FOR 50K
