#config_version=2
Images:
    mpf_logo:
        file: mission_pinball_flag_dmd.png
        alpha_color: 0
        target: dmd
    scribble:
        file: scribble.bmp
        alpha_color: 0
        target: dmd
    p_roc:
        file: p_roc.dmd
        alpha_color: 0
    mpf_background:
        file: mpf_background_800_600.bmp
    backglass:
        file: sttng_background.bmp
    death:
        file: death.png
        target: dmd

Animations:
    rolling_ball:
        file: rolling_ball.dmd
        alpha_color: 15
