#config_version=2
# Mission Pinball Framework machine configuration file for William Star Trek: The
# Next Generation

# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/

# Created by Brian Madden & Gabe Knuth

#OSC:
#    machine_ip: 127.0.0.1
#    machine_port: 1442

Scriptlets:
    attract.Attract
    game.Game

#####################################################################
# NOTE: The section "plugins" has been deprecated. You can remove it
####################################################################
plugins:
#    #- osc.OSC
#    - auditor.Auditor
#    - logic_blocks.LogicBlocks
#    - auditor.Auditor
#    - shots.ShotController
#    - scoring.ScoreController
#    - sound.SoundController
#    - show.ShowController
##    - keyboard.Keyboard

Config:
    - hardware.yaml
    - game_logic.yaml
    - dmd.yaml
    - assets.yaml
    - window.yaml

Modes:
    #- skillshot
    - base
    - kickback
    - mission_control
    - time_rift
    - worm_hole
    - search_the_galaxy
    - battle_simulation
    - qs_challenge
    - rescue
    - asteroid_threat
    - final_frontier

Light_Scripts:
    flash:
        - tocks: 1
          color: ff
        - tocks: 1
          color: 0

