#config_version=4
# Mission Pinball Framework machine configuration file for William Star Trek: The
# Next Generation

# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/

# Created by Brian Madden & Gabe Knuth

#OSC:
#    machine_ip: 127.0.0.1
#    machine_port: 1442

scriptlets: attract.Attract game.Game

#    #- osc.OSC
#    - auditor.Auditor
#    - logic_blocks.LogicBlocks
#    - auditor.Auditor
#    - shots.ShotController
#    - scoring.ScoreController
#    - sound.SoundController
#    - show.ShowController
##    - keyboard.Keyboard

config:
- hardware.yaml
- game_logic.yaml
- dmd.yaml
- assets.yaml
- window.yaml

modes:
    #- skillshot
  - base
  - kickback
  - mission_control
  - time_rift
  - worm_hole
  - search_the_galaxy
  - battle_simulation
  - qs_challenge
  - rescue
  - asteroid_threat
  - final_frontier

shows:
  flash:
  - time: 0
    lights:
      (lights): ff
  - time: '+1'
    lights:
      (lights): 0

  - time: '+1'
widget_styles:
  text_default:
    font_name: Quadrit
    font_size: 10
    crop_top: 2
    crop_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    crop_top: 3
    crop_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    crop_top: 2
    crop_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    crop_top: 1
    crop_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    crop_top: 2
    crop_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
