#config_version=4
hardware:
  platform: fast

fast:
  port0_name: /dev/ttyO2
  port0_baud: 921600
  port1_name: /dev/ttyO1
  port1_baud: 460800
  main_port: 0
  led_port: 1
  dmd_port: 1 

config:
- config.yaml
