#config_version=2
Window:
    width: 1680
    height: 1050
    title: "Star Trek: The Next Generation"
    resizable: yes
    frame: yes
    fullscreen: yes
    fps: auto
    quit_on_close: True
    elements:

      - type: VirtualDMD
        width: 1024
        height: 256
        h_pos: center
        v_pos: bottom
        y: -25
        pixel_color: ff5500
        dark_color: 220000
        priority: 1
        pixel_spacing: 1

      - type: Image
        image: backglass
        v_pos: top
        h_pos: center
        priority: 0

      - type: Shape
        shape: box
        width: 1030
        height: 262
        priority: 1
        thickness: 2
        v_pos: bottom
        y: -23
        h_pos: center
        color: aaaaaa

#####################################################################
# NOTE: The section "plugins" has been deprecated. You can remove it
####################################################################
plugins:
#    - keyboard.Keyboard
