# config_version=3

config:
  - hardware.yaml
  - window.yaml
  - keyboard.yaml

modes:
  # - test
  - base
  - skillshot
  - game_mode_selector
  - castle_grunewald
  # - choose_wisely
  # - three_challenges
  # - tank_chase
  - high_score
  - tilt
#  - credits

sound_system:
  tracks:
    voice:
      volume: 1
      priority: 2
      simultaneous_sounds: 1
      preload: no
    sfx:
      volume: 1
      priority: 1
      preload: no
      simultaneous_sounds: 3
  stream:
    name: music
    priority: 0

  buffer: 512
  frequency: 44100
  channels: 1
  initial_volume: 1
  volume_steps: 20

sound_player:
  player added:
    sound: whip_1
    start_events: player_add_success

event_player:
   pop_deflector:
       coil_c_ark_deflector_pulse
       coil_c_ark_deflector_hold_enable
       coil_c_deflector_motor_enable
   drop_deflector:
       coil_c_deflector_motor_disable
       coil_c_ark_deflector_hold_disable
   pop_portal:
       coil_c_vuk_portal_pulse

credits:
  max_credits: 12
  free_play: no
  service_credits_switch: exit
  switches:
    - switch: coin1
      type: money
      value: .25
    - switch: coin2
      type: money
      value: .25
    - switch: coin3
      type: token
      value: 1
    - switch: coin4
      value: 1
      type: money
  pricing_tiers:
    - price: .50
      credits: 1
    - price: 2
      credits: 5
  fractional_credit_expiration_time: 15m
  credit_expiration_time: 2h
  persist_credits_while_off_time: 1h
  free_play_string: FREE PLAY
  credits_string: CREDITS