# config_version=3

# MPF hardware config for Williams Indiana Jones: The Pinball Adventure

switches:
    right_flipper:
        number: SF2
        tags: player, right_flipper
    left_flipper:
        number: SF4
        tags: player, left_flipper
    adventure_e1:
        number: SF5
        type: 'NC'
    adventure_n:
        number: SF6
        type: 'NC'
        tags: playfield_active
    adventure_t:
        number: SF7
        type: 'NC'
        tags: playfield_active
    left_ramp_made:
        number: SF8
        tags: playfield_active

    coin1:
      number: SD1
    coin2:
      number: SD2
    coin3:
      number: SD3
    coin4:
      number: SD4

    exit:
        number: SD5
    down:
        number: SD6
    up:
        number: SD7
    enter:
        number: SD8

    #Regular Switches
    totem_drop_target:
        number: S11
        tags: playfield_active
    super_ball:
        number: S12, player
    start:
        number: S13
        tags: start, player
    plumb_bob:
        number: S14
        tags: tilt_warning
    left_outlane:
        number: S15
        tags: playfield_active
    left_inlane:
        number: S16
        tags: playfield_active
    right_inlane:
        number: S17
        tags: playfield_active
    right_outlane_top:
        number: S18
        tags: playfield_active
    slam_tilt:
        number: S21
        tags: slam_tilt
    coin_door_closed:
        number: S22
    ticket_opto:
        number: S23
    always_closed:
        number: S24
        tags: always_closed
    indy_i:
        number: S25
        tags: playfield_active
    indy_n:
        number: S26
        tags: playfield_active
    indy_d:
        number: S27
        tags: playfield_active
    indy_y:
        number: S28
        tags: playfield_active
    mode_hole:
        number: S31
        tags: playfield_active
    exit_idol:
        number: S32
        tags: playfield_active
    left_slingshot:
        number: S33
        tags: playfield_active
    gun_trigger:
        number: S34
        tags: launch, player
    left_jet:
        number: S35
        tags: playfield_active
    right_jet:
        number: S36
        tags: playfield_active
    bottom_jet:
        number: S37
        tags: playfield_active
    center_standup:
        number: S38
        tags: playfield_active
    left_ramp_enter:
        number: S41
        type: NC
        tags: playfield_active
    right_ramp_enter:
        number: S42
        type: NC
        tags: playfield_active
    top_idol_enter:
        number: S43
        type: 'NC'
    right_popper:
        number: S44
        type: 'NC'
    center_enter:
        number: S45
        type: 'NC'
    top_post:
        number: S46
    subway_lockup:
        number: S47
        type: 'NC'
    right_slingshot:
        number: S48
        tags: playfield_active
    adventure_u:
        number: S51
        tags: playfield_active
    adventure_r:
        number: S52
        tags: playfield_active
    adventure_e2:
        number: S53
        tags: playfield_active
    left_Loop_top:
        number: S54
        tags: playfield_active
    left_Loop_bottom:
        number: S55
        tags: playfield_active
    right_Loop_top:
        number: S56
        tags: playfield_active
    right_Loop_Bottom:
        number: S57
        tags: playfield_active
    right_Outlane_Bottom:
        number: S58
        tags: playfield_active
    adventure_A:
        number: S61
        tags: playfield_active
    adventure_D:
        number: S62
        tags: playfield_active
    adventure_V:
        number: S63
        tags: playfield_active
    captive_Ball_Back:
        number: S64
        tags: playfield_active
    mini_Top_Left:
        number: S65
        tags: playfield_active
    mini_Middle_Top_Left:
        number: S66
        tags: playfield_active
    mini_Middle_Bottom_Left:
        number: S67
        tags: playfield_active
    mini_Bottom_Left:
        number: S68
        tags: playfield_active
    captive_Ball_Front:
        number: S71
        type: 'NC'
        tags: playfield_active
    mini_Top_Hole:
        number: S72
        type: 'NC'
        tags: playfield_active
    mini_Bottom_Hole:
        number: S73
        type: 'NC'
        tags: playfield_active
    right_Ramp_Made:
        number: S74
        tags: playfield_active
    mini_Top_Right:
        number: S75
        tags: playfield_active
    mini_Middle_Top_Right:
        number: S76
        tags: playfield_active
    mini_Middle_Bottom_Right:
        number: S77
        tags: playfield_active
    mini_Bottom_Right:
        number: S78
        tags: playfield_active
    trough1:
        number: S81
        type: 'NC'
        tags: playfield_active
    trough2:
        number: S82
        type: 'NC'
    trough3:
        number: S83
        type: 'NC'
    trough4:
        number: S84
        type: 'NC'
    trough5:
        number: S85
        type: 'NC'
    trough6:
        number: S86
        type: 'NC'
    trough_jam:
        number: S87
        type: 'NC'
    shooter_lane:
        number: S88
    wheel_position1:
        number: S91
        type: 'NC'
    wheel_Position2:
        number: S92
        type: 'NC'
    wheel_Position3:
        number: S93
        type: 'NC'
    mini_Left_Limit:
        number: S94
        type: 'NC'
    mini_Right_Limit:
        number: S95
        type: 'NC'

coils:
    flipper_left_main:
        number: FLLM
        pulse_ms: 30
    flipper_left_hold:
        number: FLFH
    flipper_right_main:
        number: FLRM
        pulse_ms: 30
    flipper_right_hold:
        number: FLRH
        pulse_ms: 0
    divertor_Main:
        number: FURM
    divertor_Hold:
        number: FURH
    topLockup_Main:
        number: FULM
    topLockup_Hold:
        number: FULH
    ball_Popper:
        number: C01
    ball_Launch:
        number: C02
        pulse_ms: 20
    totem_drop_up:
        number: C03
        pulse_ms: 19
    trough:
        number: C04
        pulse_ms: 30
    center_drop_bank:
        number: C05
        pulse_ms: 35
    idol_Release:
        number: C06
    knocker:
        number: C07
    mode_hole_eject:
        number: C08
    left_Jet:
        number: C09
        pulse_ms: 20
    right_Jet:
        number: C10
        pulse_ms: 20
    bottom_Jet:
        number: C11
        pulse_ms: 20
    left_Slingshot:
        number: C12
        pulse_ms: 20
    right_Slingshot:
        number: C13
        pulse_ms: 20
    left_Control_Gate:
        number: C14
    right_Control_Gate:
        number: C15
    totem_drop_down:
        number: C16
    mini_Motor_Left:
        number: C22
    mini_Motor_Right:
        number: C23
    subway_Release:
        number: C28
    wheel_Motor:
        number: C42

flashers:
    EternalLife:
        number: C17
    LiteJackpot:
        number: C18
    SuperJackpot:
        number: C19
    Jackpot:
        number: C20
    path_of_adventure:
        number: C21
    PlaneGuns:
        number: C24
    DogFight:
        number: C25
    RightRamp:
        number: C26
    LeftRamp:
        number: C27
    LeftSide:
        number: C37
    RightSide:
        number: C38
    Special:
        number: C39
    Totem:
        number: C40
    JackpotMultiplier:
        number: C41

matrix_lights:
    mode_start:
        number: L11
    hand_of_fate:
        number: L12
    extra_ball:
        number: L13
    adventure_v:
        number: L14
    adventure_d:
        number: L15
    adventure_a:
        number: L16
    shoot_again:
        number: L17
    get_the_idol:
        number: L18
    tank_chase:
        number: L21
    adventure_t:
        number: L22
    adventure_e1:
        number: L23
    adventure_n:
        number: L24
    steal_the_stones:
        number: L25
    grail_jackpot:
        number: L26
    streets_of_cairo:
        number: L27
    stones_jackpot:
        number: L28
    left_ramp_arrow:
        number: L31
    castle_grunewald:
        number: L32
    left_plane_top:
        number: L33
    monkey_brains:
        number: L34
    left_plane_middle:
        number: L35
    sallah:
        number: L36
    bonus_4X:
        number: L37
    left_plane_bottom:
        number: L38
    mine_cart:
        number: L41
    ark_jackpot:
        number: L42
    raven_bar:
        number: L43
    right_plane_middle:
        number: L44
    bonus_6X:
        number: L45
    right_plane_bottom:
        number: L46
    well_of_souls:
        number: L47
    left_loop:
        number: L48
    choose_wisely:
        number: L51
    right_plane_top:
        number: L52
    rope_bridge:
        number: L53
    adventure_u:
        number: L54
        debug: yes
    adventure_r:
        number: L55
    adventure_e2:
        number: L56
    three_challenges:
        number: L57
    right_loop:
        number: L58
    indy_i:
        number: L61
    indy_n:
        number: L62
    indy_d:
        number: L63
        debug: yes
    indy_y:
        number: L64
    willie:
        number: L65
    bonus_2X:
        number: L66
    shorty:
        number: L67
    right_ramp_arrow:
        number: L68
    mini_yop_left:
        number: L71
    mini_top_right:
        number: L72
    mini_middle_top_left:
        number: L73
    mini_middle_top_right:
        number: L74
    mini_top_arrow:
        number: L75
    marrion:
        number: L76
    bonus_8X:
        number: L77
    dr_jones:
        number: L78
    mini_middle_bottom_left:
        number: L81
    mini_middle_bottom_right:
        number: L82
    mini_bottom_left:
        number: L83
    mini_bottom_right:
        number: L84
    mini_bottom_arrow:
        number: L85
    totem_top_arrow:
        number: L86
    center_lock:
        number: L87
    start_button:
        number: L88

flippers:
    left_flipper:
        main_coil: flipper_left_main
        hold_coil: flipper_left_hold
        activation_switch: left_flipper
    right_flipper:
        main_coil: flipper_right_main
        hold_coil: flipper_right_hold
        activation_switch: right_flipper
        #debounced: false
        #pulse_ms: 40

autofire_coils:
  # left_jet:
  #   coil: left_jet
  #   switch: left_jet
  right_jet:
    coil: right_jet
    switch: right_jet
  bottom_jet:
    coil: bottom_jet
    switch: bottom_jet
  left_slingshot:
    coil: left_slingshot
    switch: left_slingshot
  right_slingshot:
    coil: Right_slingshot
    switch: right_slingshot

ball_devices:
  trough:
    ball_switches: trough1, trough2, trough3, trough4, trough5, trough6, trough_jam
#    entrance_count_delay: 300ms
    eject_coil: trough
    confirm_eject_type: target
    eject_targets: plunger_lane
    jam_switch: trough_jam
    tags: trough, home, drain
    debug: yes
  plunger_lane:
    ball_switches: shooter_lane
#    entrance_count_delay: 300ms
    mechanical_eject: True
    eject_coil: ball_launch
    confirm_eject_type: target
    exit_count_delay: 500ms
    tags: ball_add_live
    debug: yes
#    eject_events: sw_launch
  mode_hole:
    ball_switches: mode_hole
    eject_coil: mode_hole_eject
    debug: yes

shots:
  indy_i:
    switch: indy_i
    light: indy_i
    debug: yes
    reset_events:
  indy_n:
    switch: indy_n
    light: indy_n
    debug: yes
    reset_events:
  indy_d:
    switch: indy_d
    light: indy_d
    debug: yes
    reset_events:
  indy_y:
    switch: indy_y
    light: indy_y
    debug: yes
    reset_events:
  adventure_a:
    switch: adventure_a
    light: adventure_a
  adventure_d:
    switch: adventure_d
    light: adventure_d
  adventure_v:
    switch: adventure_v
    light: adventure_v
  adventure_e1:
    switch: adventure_e1
    light: adventure_e1
  adventure_n:
    switch: adventure_n
    light: adventure_n
  adventure_t:
    switch: adventure_t
    light: adventure_t
  adventure_u:
    switch: adventure_u
    light: adventure_u
  adventure_r:
    switch: adventure_r
    light: adventure_r
  adventure_e2:
    switch: adventure_e2
    light: adventure_e2
  right_loop:
    switch_sequence: right_loop_bottom, right_loop_top
    time: 2s
  left_loop:
    switch_sequence: left_loop_bottom, left_loop_top
    time: 2s
  right_ramp:
    switch_sequence: right_ramp_enter, right_Ramp_Made
    time: 2s
    debug: yes
  left_ramp:
    switch_sequence: left_ramp_enter, left_ramp_made
    time: 2s

  three_test:
    switch_sequence: right_inlane, right_outlane_top, right_Outlane_Bottom
    time: 3s
    debug: true

shot_groups:
  indy_lanes:
    shots: indy_i, indy_n, indy_d, indy_y
    debug: yes
#  adventure:
#    shots: adventure_a, adventure_d, adventure_v, adventure_e1, adventure_n, adventure_t, adventure_u, adventure_r, adventure_e2
#    debug: yes

drop_targets:
  e:
    switch: adventure_e1
    reset_events:
  n:
    switch: adventure_n
    reset_events:
  t:
    switch: adventure_t
    reset_events:
  totem:
    switch: totem_drop_target
    reset_coil: totem_drop_up
    knockdown_coil: totem_drop_down
    reset_events:

drop_target_banks:
  ent:
    drop_targets: e, n, t
    reset_coil: center_drop_bank
    debug: true
    reset_events:
      #ball_started: 1s

virtual_platform_start_active_switches:
#    trough1
    trough2
    trough3
    trough4
    trough5
    trough6
    mode_hole



dmd:
    physical: yes
    width: 128
    height: 32

gis:
  top_playfield:
    number: g01
  bottom_playfield:
    number: g02
  insert_top:
    number: g03
  insert_bottom:
    number: g04
  return_lane_coin:
    number: g05

shot_profiles:
  test_2:
#    lights_when_disabled: yes
#    block: no
#    loop: yes
    states:
      - name: lit
        light_script: flash
        repeat: yes
        tocks_per_sec: 2
      - name: hit
        light_script: "on"
  test_10:
#    lights_when_disabled: yes
#    block: no
#    loop: yes
    states:
      - name: lit
        light_script: flash
        repeat: yes
        tocks_per_sec: 10
      - name: hit
        light_script: "on"