# config_version=4
keyboard:
  s:
    switch: start
  l:
    switch: gun_trigger
  slash:
    switch: right_flipper
  z:
    switch: left_flipper
  x:
    switch: left_slingshot
  period:
    switch: right_slingshot

  shift+1:
    switch: trough1
    toggle: true
  shift+2:
    switch: trough2
    toggle: true
  shift+3:
    switch: trough3
    toggle: true
  shift+4:
    switch: trough4
    toggle: true
  shift+5:
    switch: trough5
    toggle: true
  shift+6:
    switch: trough6
    toggle: true
  shift+7:
    switch: trough_jam
  shift+8:
    switch: shooter_lane
    toggle: true

  0:
    event: b_reset

  1:
    switch: adventure_a
  2:
    switch: adventure_d
  3:
    switch: adventure_v
  4:
    switch: adventure_e1
    toggle: true
  5:
    switch: adventure_n
    toggle: true
  6:
    switch: adventure_t
    toggle: true
  7:
    switch: adventure_u
  8:
    switch: adventure_r
  9:
    switch: adventure_e2
  u:
    switch: indy_i
  i:
    switch: indy_n
  o:
    switch: indy_d
  p:
    switch: indy_y
  m:
    switch: mode_hole
    toggle: true
  t:
    switch: plumb_bob
  shift-t:
    switch: slam_tilt
