# config_version=4
config:
- config.yaml

switch_player:
  start_event: machine_reset_phase_3
  start_delay: 1s
  steps:
      # player 1 ball 1
    - time: 600ms
      switch: start
      action: hit
    - time: 100ms
      switch: trough1
      action: deactivate
    - time: 1s
      switch: shooter_lane
      action: activate
    - time: 1s
      switch: gun_trigger
      action: hit
    - time: 100ms
      switch: gun_trigger
      action: deactivate
    - time: 100ms
      switch: right_flipper
      action: hit
    - time: 100ms
      switch: indy_i
      action: hit
    - time: 500ms
      check_light: indy_d
      value: 0
