Mode:
    start_events: sw_left_cannon_loaded
    stop_events: timer_left_cannon_launched_complete
    priority: 200

Slide_Player:
    mark_cleared:
      - type: Text
        text: "Pull the trigger!"
        v_pos: center
        transition:
            type: move_in
            direction: top
    mark_closed:
      - type: Text
        text: "Wait for it..."
        v_pos: center
        transition:
            type: move_in
            direction: top

Timers:
    left_cannon_loaded:
        start_value: 5
        direction: down
        control_events:
          - event: mode_left_cannon_started
            action: start
            ### When this completes, it needs to play a sound to alert player to
            ### pull the trigger

Show_Player:
    mode_left_cannon_enabled:
      - show: flash_left_cannon
        repeat: yes
        tocks_per_sec: 4
    mode_left_cannon_stopped:
      - show: flash_kickback
        action: stop


