#config_version=4
mode:
    start_events: ball_starting
    priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
      - type: text
        text: PLAYER (number)
        y: bottom
        x: left
      - type: text
        text: BALL (ball)
        y: bottom
        x: right
