language: python
python:
- 3.4
install:
- pip install ruamel.yaml
- pip install coveralls
- pip install pyserial
- pip install https://github.com/missionpinball/mpf/zipball/dev
script: coverage run -m unittest discover
after_success: coveralls