language:
  python

python:
  - 3.4

install:
- pip3 install coveralls
- pip3 install https://github.com/missionpinball/mpf/zipball/${TRAVIS_BRANCH} || pip3 install https://github.com/missionpinball/mpf/zipball/dev;
- pip3 install https://github.com/missionpinball/mpf-mc/zipball/${TRAVIS_BRANCH} || pip3 install https://github.com/missionpinball/mpf-mc/zipball/dev;
script:
  coverage run -m unittest discover
after_success:
  coveralls
