dist: trusty
sudo: required
os: linux
env: LINUX=ubuntu:16.04
language: python

services:
  - docker

before_install:
  - git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf.git _mpf || https://github.com/missionpinball/mpf.git _mpf || git clone --recursive --branch dev https://github.com/missionpinball/mpf.git _mpf;
  - git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-mc.git _mpf-mc || git clone --recursive --branch dev https://github.com/missionpinball/mpf_mc.git _mpf-mc;
  - git clone --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer || git clone --recursive --branch dev https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer;

install:
- pip3 install --upgrade coveralls

script:
- docker run -v /dev/snd:/dev/snd --lxc-conf='lxc.cgroup.devices.allow = c 116:* rwm' -v $PWD:$PWD -w $PWD $LINUX /bin/sh -c "_mpf_installer/install-mpf && pip3 install --upgrade coveralls && apt-get install -y xvfb && pip3 install -e _mpf/ && pip3 install _mpf-mc/ && export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX && export PYTHONPATH=$PYTHONPATH:$(pwd) && coverage3 run --concurrency=thread -m unittest discover;";

after_success:
  coveralls
