language:
  python

python:
  - 3.4

install:
- pip3 install coveralls
- git clone --branch $TRAVIS_BRANCH https://github.com/missionpinball/mpf.git || git clone --branch dev https://github.com/missionpinball/mpf.git
- git clone --branch $TRAVIS_BRANCH https://github.com/missionpinball/mpf-mc.git || git clone --branch dev https://github.com/missionpinball/mpf-mc.git
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)/mpf-mc:$(pwd)/mpf; 
script:
  coverage run -m unittest discover
after_success:
  coveralls
