language:
  python

python:
  - 3.4

install:
- yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots;
- sudo apt-get update;
- sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev gstreamer0.10-plugins-{good,base,bad,ugly} libgstreamer0.10-dev libxine1-ffmpeg libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libX11-dev libmtdev-dev build-essential libgl1-mesa-dev libgles2-mesa-dev;
- sudo apt-get -y install xvfb pulseaudio;
- pip3 install --upgrade cython pillow coveralls setuptools;
- git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf.git ../_mpf || git clone --recursive --branch `python3 ../get_version.py` https://github.com/missionpinball/mpf.git ../_mpf || git clone --recursive --branch dev https://github.com/missionpinball/mpf.git ../_mpf;
- pip3 install -e ../_mpf/;
- pip3 install kivy;
- pip3 install https://github.com/missionpinball/mpf-mc/zipball/${TRAVIS_BRANCH} || pip3 install https://github.com/missionpinball/mpf-mc/zipball/dev;

before_script:
- export DISPLAY=:99.0;
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
- export PYTHONPATH=$PYTHONPATH:$(pwd);

script:
- coverage3 run --concurrency=thread -m unittest discover -v;

after_success:
  coveralls
