#config_version=3
show_player:
  mode_attract_started:
    - show: attract_dmd_loop
      repeat: yes

light_player:
  mode_attract_started:
    - show: multiball_sweep
      repeat: yes
    - show: random_flashing
      repeat: yes
    - show: freeze_sweep
      repeat: yes
    - show: car_crash_sweep
      repeat: yes
    - show: middle_circle_sweep
      repeat: yes
    - show: right_orbit_sweep
      repeat: yes
    - show: standup_sweep
      repeat: yes
    - show: center_red_sweep
      repeat: yes
    - show: center_ramp_sweep
      repeat: yes
    - show: top_lanes_sweep
      repeat: yes
    - show: claw_cycle
      repeat: yes
    - show: inlane_alternate
      repeat: yes
    - show: flashers
      repeat: yes
