#config_version=4

show_player:
  mode_attract_started:
    attract_display:
      loops: -1
      speed: 1         

    drop_target_sweep:
      loops: -1
      speed: 5
    chain_sweep:
      loops: -1
      speed: 8
    flipper_area_flash:
      loops: -1
      speed: 4
    lock_sweep:
      loops: -1
      speed: 5
    crime_sweep:
      loops: -1
      speed: 5
    perp_sweep:
      loops: -1
      speed: 3
    random_blinking:
      loops: -1
      speed: 4
  mode_attract_stopped:
    attract_display:
      action: stop
    drop_target_sweep:
      action: stop
    chain_sweep:
      action: stop
    flipper_area_flash:
      action: stop
    lock_sweep:
      action: stop
    crime_sweep:
      action: stop
    perp_sweep:
      action: stop
    random_blinking:
      action: stop

