# config_version=4

hardware:
  platform: smart_virtual
  driverboards: virtual

config:
- hardware.yaml
- shots.yaml
- keyboard.yaml

mpf:
  default_pulse_ms: 20

game:
  balls_per_game: 3
  max_players: 4
#    player_controlled_eject_tag: plunger

modes:
- base
- claw_lit_for_major_mode
- mode1_acmag
- skillshot
- bonus
- high_score
- tilt
#  - credits

scriptlets: add_a_ball.AddABall claw.Claw

window:
  width: 800
  height: 600
  minimum_width: 200
  minimum_height: 100
  borderless: true
  fullscreen: false
  rotation: 0
  title: Demo Man
  show_cursor: false
  source_display: window
  dpi: 96
  scale_contents: true

displays:
  window:
    height: 600
    width: 800
    default: true
  dmd:
    width: 128
    height: 32

slides:
  slide_1: []
keyboard:
  g:
    mc_event: event1
  h:
    mc_event: event2

slide_player:
  display_window_initialized: slide_1
text_styles:
  default:
    font_name: Quadrit
    font_size: 10
    crop_top: 2
    crop_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    crop_top: 3
    crop_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    crop_top: 2
    crop_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    crop_top: 1
    crop_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    crop_top: 2
    crop_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
#animations:
#  fade_in:
#    property: opacity
#    start: 0
#    value: 1
#    duration: 1s
#    timing: with_previous
#    repeats: 0
#
#  multi:
#  - property: opacity
#    value: 1
#    duration: 1s
#  - property: opacity
#    value: 0
#    duration: 100ms
#    timing: after_previous
#    repeats: -1
