# config_version=4

scriptlets: attract.Attract deadworld.Deadworld add_a_ball.AddABall

config:
- dmd.yaml
- game_logic.yaml
- hardware.yaml
- languages.yaml
- sound.yaml
- window.yaml
text_styles:
  default:
    font_name: Quadrit
    font_size: 10
    crop_top: 2
    crop_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    crop_top: 3
    crop_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    crop_top: 2
    crop_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    crop_top: 1
    crop_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    crop_top: 2
    crop_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
