# config_version=4
game:
  balls_per_game: 3
  max_players: 4 

modes:
- skillshot
- base
- both_ramps_made

shots:
  rightramp:
    switch: rightRampExit
  leftramp:
    switch_sequence: leftRampEnter, leftRampExit
    time: 3s
  leftorbit:
    switch_sequence: leftRollover, topRightOpto
    time: 3s
  weakrightorbit:
    switch_sequence: topRightOpto, topCenterRollover
    time: 3s
  fullrightorbit:
    switch_sequence: topRightOpto, leftRollover
    time: 3s
  airraidramp:
    switch: topRampExit
  orangestandups:
    switch: threeBankTargets
  slingshot:
    switch: slingR, slingL
  inlane:
    switch: inlaneL, inlaneR, outerInlaneR
  outlane:
    switch: outlaneR, outlaneL
  droptarget:
    switch: dropTargetJ, dropTargetU, dropTargetD, dropTargetG, dropTargetE
