# config_version=4
languages: English German French

language_strings:
  french:
    press start: APPUYEZ SUR START
    free play: JEU GRATUIT
    player: JOUEUR
    ball: BALLE
  german:
    press start: START DRUEKEN
    free play: FREISPIEL
    player: SPIELER
    ball: BALL

languagesounds:
  french:
    slingshot:
      file: le_slingshot.ogg
