# config_version=4
sound_system:
  tracks:
    voice:
      volume: 1
      priority: 2
      simultaneous_sounds: 1
      preload: false
    sfx:
      volume: 1
      priority: 1
      preload: false
      simultaneous_sounds: 6
    music:
      volume: 0.5
      simultaneous_sounds: 1
  buffer: 2048  # previous value was 512
  frequency: 44100
  channels: 1
  master_volume: 1
  enabled: true
