# config_version=4
window:
  width: 800
  height: 600
  title: Mission Pinball Framework
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
config:
- keymap.yaml
displays:
  window:
    height: 600
    width: 800
slides:
  window_slide_1:
  - type: dmd
    width: 512
    height: 128
    pixel_color: ff5500
    dark_color: 220000
    z: 1
  - type: text
    style: tall title
    text: JUDGE DREDD
    anchor_x: right
    anchor_y: bottom
    y: bottom+10
    x: right-20
    font_size: 60
    z: 1
    color: ee9900

  - type: rectangle
    width: 514
    height: 130
    z: 2
    color: lime

slide_player:
  machine_reset_phase_3:
    window_slide_1:
      target: window
