#config_version=4

mode:
  start_events: ball_ending
  code: bonus.Bonus
  priority: 500
  use_wait_queue: true

slide_player:
  bonus_start: slide_6
  bonus_hits: slide_7
  bonus_slings: slide_8
  bonus_subtotal: slide_9
  bonus_multiplier: slide_10
  bonus_total: slide_11
slides:
  slide_6:
  - type: text
    text: END OF BALL BONUS
  slide_7:
  - type: text
    text: 'SLINGSHOTS: (slings)'
  slide_8:
  - type: text
    text: 'TOTAL HITS: (hits)'
  slide_9:
  - type: text
    text: 'BONUS SCORE: (points)'
    number_grouping: true
  slide_10:
  - type: text
    text: (bonus_multiplier)X
  slide_11:
  - type: text
    text: 'TOTAL BONUS: (points)'
    number_grouping: true
