#config_version=4
mode:
  start_events: ball_starting
  stop_events: timer_skillshot_hit_complete
  priority: 200

shot_groups:
  indy_lanes:
    profile: skill
    reset_events: mode_skillshot_started|1
    remove_active_profile_events: indy_lanes_skill_hit
    rotate_left_events: left_flipper_active
    rotate_right_events: right_flipper_active
    debug: true
  ure:
    shots: adventure_u, adventure_r, adventure_e2
    profile: test_2
    debug: true

shots:
  indy_i:
    advance_events: indy_i_advance
  indy_n:
    advance_events: indy_n_advance
  indy_d:
    advance_events: indy_d_advance
  indy_y:
    advance_events: indy_y_advance

random_event_player:
  mode_skillshot_started:
#    - indy_i_advance
    - indy_n_advance
    - indy_d_advance
    - indy_y_advance

event_player:
  mode_skillshot_started:
  - indy_i_advance
  - indy_i_advance

shot_profiles:
  skill:
    advance_on_hit: false
    show_when_disable: true
    block: false
    state_names_to_not_rotate: hit
    states:
    - name: unlit
      show: off
    - name: lit
      show: flash
      loops: -1
      speed: 10
    - name: hit
      show: on
scoring:
  indy_lanes_skill_lit_hit:
    score: 10000|block
  indy_lanes_default_unlit_hit:
    score: 0|block
  indy_lanes_default_lit_hit:
    score: 0|block

slide_player:
  indy_lanes_skill_lit_hit: slide_9
  indy_lanes_skill_unlit_hit: slide_10
timers:
  skillshot_hit:
    start_value: 2
    end_value: 0
    direction: down
    control_events:
    - event: indy_lanes_skill_hit
      action: start
slides:
  slide_9:
  - type: text
    text: SKILLSHOT HIT!
  slide_10:
  - type: text
    text: SKILLSHOT MISSED!

