#config_version=6

animations:
  shot_off:
    - property: opacity
      value: 0.5
      duration: 0
  shot_on:
    - property: opacity
      value: 1.0
      duration: 0
  shot_flashing:
    - property: opacity
      value: 1.0
      duration: 250ms
    - property: opacity
      value: 0.5
      duration: 250ms
      repeat: true

displays:
  main:
    width: 640
    height: 480
    default: true

slide_player:
  mode_attract_started: attract_slide
  mode_base_started: base_slide
  skillshot_lit_hit: skillshot_slide

slides:
  attract_slide:
    - type: text
      text: Attract Mode
  base_slide:
    - type: text
      text: Base Mode
    - type: text
      text: (player|score)
      number_grouping: true
      min_digits: 2
      y: 100
  skillshot_slide:
    expire: 2s
    priority: 100
    widgets:
      - type: text
        text: Skillshot Hit!

window:
  width: 640
  height: 480
  exit_on_escape: true
  source_display: main
  title: "MPF Cookbook: Skillshot with Lane Change"
