Mode:
    start_events: start_mode_rescue
    stop_events: sw_end_mission, ball_ending #the sw_end_mission switch is just for testing
    code: rescue.Rescue
    priority: 500

Slide_Player:
    mode_rescue_started:
      - type: Text
        text: "MPF to the Rescue"
        number_grouping: true
        double_zeros: true
        v_pos: center
        transition:
            type: move_in
            direction: top
