#config_version=4
mode:
    start_events: ball_starting
    priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
      - type: text
        text: PLAYER (number)
        y: bottom
        x: left
      - type: text
        text: BALL (ball)
        y: bottom
        x: right
      - type: text
        text: "POTATO VALUE: (potato)"
        y: 40%

scoring:
    s_right_inlane_active:
        score: 100
    s_flipper_lower_left_active:
        score: 1000
        potato: 1
    s_flipper_lower_right_active:
        potato: -2