# config_version=3
mode:
    start_events: enable_classic_mode
    stop_events: enable_modern_mode
    priority: 300
    stop_on_ball_end: false

show_Player:
    mode_classic_mode_start:
        classic_overlay:
          repeat: yes
    enable_modern_mode:
        classic_overlay: stop
