# config_version=3
mode:
    start_events: enable_classic_mode
    stop_events: enable_modern_mode
    priority: 300
    stop_on_ball_end: false

Show_Player:
    mode_classic_mode_start:
        - show: classic_overlay
        repeat: yes
        tocks_per_sec: 1
    enable_modern_mode:
        - show: classic_overlay
        action: stop

