# config_version=4

# Base game mode for Aztec

mode:
  start_events: ball_starting
  priority: 100

slide_player:
  player_score: slide_1
  mode_base_started: slide_2
  player_add_success: slide_3
shots:
  pops:
    switch: leftPop, rightPop, bottomPop
  slings:
    switch: leftSling, rightSling

scoring:
  targets_upperlanes_lit_complete:
    score: 5000
  targets_upperlanes_lit_hit:
    score: 100
  targets_upperlanes_unlit_hit:
    score: 1000
  shot_pops:
    score: 150
  shot_slings:
    score: 10
  balldevice_balllock_ball_enter:
    score: 2500
  shot_right1_lit:
    score: 50
  shot_right2_lit:
    score: 50
  shot_left1_lit:
    score: 50
  shot_left2_lit:
    score: 50
  shot_middle_lit:
    score: 50
  shot_upperleft_lit:
    score: 50
  shot_right1_unlit:
    score: 50
  shot_right2_unlit:
    score: 250
  shot_left1_unlit:
    score: 250
  shot_left2_unlit:
    score: 250
  shot_middle_unlit:
    score: 250
  shot_upperleft_unlit:
    score: 250 

sound_player:
  drain:
    sound: fail
    start_events: ball_drain
  slingshot:
    sound: big metal
    start_events: shot_slings
  pops:
    sound: little metal
    start_events: shot_pops
  standup_lit:
    sound: standup hit lit
    start_events: shot_left1_lit_hit, shot_left2_lit_hit
  standup_unlit:
    sound: standup hit unlit
    start_events: shot_left1_unlit_hit, shot_left2_unlit_hit
  spinner:
    sound: medium metal
    start_events: shot_spinner_unlit
slides:
  slide_1:
  - type: text
    text: '%value'
    number_grouping: true
  - type: text
    text: PLAYER (number)
    anchor_y: bottom
    anchor_x: left
    style: small
    y: bottom
    x: left
  - type: text
    text: BALL (ball)
    anchor_y: bottom
    anchor_x: right
    style: small

    y: bottom
    x: right
  slide_2:
  - type: text
    text: (score)
    number_grouping: true
    min_digits: 2
  - type: text
    text: PLAYER (number)
    anchor_y: bottom
    anchor_x: left
    style: small
    y: bottom
    x: left
  - type: text
    text: BALL (ball)
    anchor_y: bottom
    anchor_x: right
    style: small

    y: bottom
    x: right
  slide_3:
  - type: text
    text: PLAYER %num ADDED
    priority: 1   

