Mode:
    start_events: start_mode_final_frontier
    stop_events: sw_end_mission, ball_ending #the sw_end_mission switch is just for testing
    code: final_frontier.FinalFrontier
    priority: 500

Slide_Player:
    mode_final_frontier_started:
      - type: Text
        text: "Final Frontier"
        number_grouping: true
        double_zeros: true
        v_pos: center
        transition:
            type: move_in
            direction: top
