#config_version=3
mode:
    start_events: ball_starting
    priority: 100

slide_player:
  mode_base_started:
    slide: score
    transition:
      type: move_in

slides:
  score:
    - type: text
      text: "%score%"
      number_grouping: true
      min_digits: 2

    - type: text
      text: PLAYER %number%
      y: 0
      anchor_y: bottom
      x: 0
      anchor_x: left
#      font: small
    - type: text
      text: BALL %ball%
      anchor_y: bottom
      anchor_x: right
      y: 0
      x: 100%
#      font: small

scoring:
  ball_started:
    score: 100
  s_left_flipper_active:
    score: 1000
