# config_version=4
mode:
  start_events: ball_starting
  priority: 100

drop_target_banks:
  ent:
    reset_events:
      ent_drop_target_down_complete: 1s

shot_groups:
  indy_lanes:
    rotate_left_events: left_flipper_active
    rotate_right_events: right_flipper_active
    reset_events:
      indy_lanes_default_lit_complete: 1s
    #enable_events: ball_started
    #disable_events: ball_ending
    #profile: indy_lanes
  ure:
    shots: adventure_u, adventure_r, adventure_e2
    profile: test_10
    debug: true

shot_profiles:
  indy_lanes:
    states:
    - name: unlit
      show: off
    - name: lit
      show: flash_to_on
      loops: false
      hold: true
      speed: 10            

shows:
  flash_to_on:
  - time: 0
    lights:
      (lights): ff
  - time: '+1'
    lights:
      (lights): 0
  - time: '+2'
    lights:
      (lights): ff
  - time: '+2'
    lights:
      (lights): 0
  - time: '+4'
    lights:
      (lights): ff
  - time: '+4'
    lights:
      (lights): 0
  - time: '+1'
    lights:
      (lights): ff

  - time: '+1'
event_player:
  player_add_success: player_1_multiplayer_slide
  player_1_ball_started: player_1_multiplayer_slide

slide_player:
  single_player_ball_started: slide_2
  player_1_multiplayer_slide: slide_3
  player_2_ball_started: slide_4
  player_3_ball_started: slide_5
  player_4_ball_started: slide_6
  ball_save_default_saving_ball: slide_7
sound_player:
  waiting_to_launch_a_ball:
    sound: waiting_to_launch_a_ball
    start_events: mode_base_started
    stop_events: sw_plunger
    loops: -1
#    volume: 0.5
  main_theme:
    sound: main_theme
    start_events: gun_trigger_active
    loops: -1
  gun_trigger:
    sound: shotgun_1
    start_events: gun_trigger_active

scoring:
  indy_lanes_default_unlit_hit:
    score: 5000
  indy_lanes_default_lit_hit:
    score: 100
  indy_lanes_default_lit_complete:
    score: 10000

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_plunger_lane_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    debug: true
slides:
  slide_2:
  - type: text
    text: (score)
    number_grouping: true
    min_digits: 2
    y: middle+2
      #persist_slide: yes
    style: tall title
  - type: text
    text: BALL (ball)    FREE PLAY
    anchor_y: bottom
    style: small

    y: bottom
  slide_3:
  - type: text
    text: (player1|score)
      #font: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: left
    y: top
    x: left
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    y: top
    x: right
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: left
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: left
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: right
  - type: text
    text: BALL (ball)    FREE PLAY
    anchor_y: bottom
    style: small

    y: bottom
  slide_4:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: left
    y: top
    x: left
  - type: text
    text: (player2|score)
#      font: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    y: top
    x: right
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: left
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: left
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: right
  - type: text
    text: BALL (ball)    FREE PLAY
    anchor_y: bottom
    style: small

    y: bottom
  slide_5:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: left
    y: top
    x: left
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    y: top
    x: right
  - type: text
    text: (player3|score)
#      font: medium
    anchor_y: bottom
    anchor_x: left
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: left
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: right
  - type: text
    text: BALL (ball)    FREE PLAY
    anchor_y: bottom
    style: small

    y: bottom
  slide_6:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: left
    y: top
    x: left
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    y: top
    x: right
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: left
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: left
  - type: text
    text: (player4|score)
#      font: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    number_grouping: true
    min_digits: 2
    x: right
  - type: text
    text: BALL (ball)    FREE PLAY
    anchor_y: bottom
    style: small

    y: bottom
  slide_7:
  - type: text
    text: BALL SAVED
show_player:
  indy_lanes_default_lit_complete:
    indy_Lanes_complete:
      speed: 20
      loops: -1
      priority: 1
  ball_save_default_enabled:
    flash:
      lights: shoot_again
      speed: 10
      key: ball_saves
  ball_save_default_disabled:
    ball_saves:
      action: stop

