Mode:
    start_events: ball_starting
    priority: 100

Slide_Player:
    mode_base_started:
      - type: Text
        text: "Pull Trigger To Begin"
        number_grouping: true
        double_zeros: true
        v_pos: center
        transition:
            type: move_in
            direction: top
      - type: Text
        text: PLAYER %number%
        v_pos: bottom
        h_pos: left
        font: small
      - type: Text
        text: BALL %ball%
        v_pos: bottom
        h_pos: right
        font: small
    balldevice_bd_catapult_ball_eject_attempt:
        - type: Text
          text: "%score%"
          number_grouping: true
          double_zeroes: true
          v_pos: center
    ball_started:
        text: PLAYER %player BALL %ball
    player_score:
      - type: Text
        text: "%score%"
        number_grouping: true
        v_pos: center
      - type: Text
        text: PLAYER %number%
        v_pos: bottom
        h_pos: left
        font: small
      - type: Text
        text: BALL %ball%
        v_pos: bottom
        h_pos: right
        font: small

Logic_Blocks:
    Accruals:
        lb_left_cannon_loaded:
            # Works, but only once. Doesn't reset when complete
            events:
              - shot_rightRamp
                shot_rightOrbit
                shot_leftOrbit
                shot_leftRamp
                shot_middleRamp
                shot_commandDecision
                shot_startMission
            events_when_complete: time_rifting
            enable_events: mode_time_rift_started
            reset_each_ball: yes
            restart_on_complete: yes
            disable_on_complete: no