#config_version=4

show_player:
  mode_attract_started:
    abcd_sweep:
      loops: -1
      speed: 10
    planet_pulse:
      loops: -1
    spaceship_pulse:
      loops: -1
    jupiter_red_spot:
      loops: -1
    stars:
      loops: -1