#config_version=4

config:
- window.yaml

hardware:
  platform: fast
  driverboards: wpc

fast:
  ports: com4, com5, com6

modes:
- base

coils:
  backboxmotor:
    number: C01
    allow_enable: true
  droptargetreset:
    number: C02
    pulse_ms: 30
  leftjuggler:
    number: C04
    pulse_ms: 18
  rightjuggler:
    number: C05
    pulse_ms: 20
#    ferrisWheels:
#        number: C06
#        allow_enable: True
  knocker:
    number: C07
    pulse_ms: 20
  outhole:
    number: C09
    pulse_ms: 20
  ballrelease:
    number: C10
    pulse_ms: 20
  leftslingshot:
    number: C11
    pulse_ms: 20
  rightslingshot:
    number: C12
    pulse_ms: 20
  leftpop:
    number: C13
    pulse_ms: 20
  rightpop:
    number: C14
    pulse_ms: 20
  bottompop:
    number: C15
    pulse_ms: 20

switches:
  rightflipper:
    number: S11
  leftflipper:
    number: S12
  start:
    number: S13
    tags: start
  plumbbob:
    number: S14
    tags: tilt
  outhole:
    number: S15
  trough1:
    number: S16
  trough2:
    number: S17
  trough3:
    number: S18
  slamtilt:
    number: S21
    tags: slam_tilt
  coindoorclosed:
    number: S22
  ticket:
    number: S23
    tags: playfield_active
  alwaysclosed:
    number: S24
    type: NC
  rightslingshot:
    number: S25
    tags: playfield_active
  rightinlane:
    number: S26
    tags: playfield_active
  rightoutlane:
    number: S27
    tags: playfield_active
  shooterlane:
    number: S28
  ferriswheel:
    number: S31
    tags:
  leftdrop1:
    number: S33
    tags: playfield_active
  leftdrop2:
    number: S34
    tags: playfield_active
  leftdrop3:
    number: S35
    tags: playfield_active
  leftslingshot:
    number: S36
    tags: playfield_active
  leftinlane:
    number: S37
    tags: playfield_active
  leftoutlane:
    number: S38
    tags: playfield_active
  rightstandup1:
    number: S42
    tags: playfield_active
  rightstandup2:
    number: S43
    tags: playfield_active
  rightstandup3:
    number: S44
    tags: playfield_active
  rightstandup4:
    number: S45
    tags: playfield_active
  leftpop:
    number: S51
    tags: playfield_active
  rightpop:
    number: S52
    tags: playfield_active
  bottompop:
    number: S53
    tags: playfield_active
  dunkthedummy:
    number: S55
    tags: playfield_active
  leftjuggler:
    number: S56
  rightjuggler:
    number: S57
  hurricaneentry:
    number: S61
    tags: playfield_active
  hurricaneexit:
    number: S62
    tags: playfield_active
  cometentry:
    number: S63
    tags: playfield_active
  cometexit:
    number: S64
    tags: playfield_active
  coin1:
    number: SD1
  coin2:
    number: SD2
  coin3:
    number: SD3
  coin4:
    number: SD4
  esc:
    number: SD5
  down:
    number: SD6
  up:
    number: SD7
  enter:
    number: SD8

matrix_lights:
  clownlefteye:
    number: L11
  clownrighteye:
    number: L12
  clownleftcheek:
    number: L13
  clownnose:
    number: L14
  clownrightcheek:
    number: L15
  clownmouth:
    number: L16
  leftoutlane:
    number: L17
  leftinlane:
    number: L18
  bonus2x:
    number: L21
  bonus3x:
    number: L22
  bonus4x:
    number: L23
  bonus5x:
    number: L24
  bonus6x:
    number: L25
  leftdrop1:
    number: L26
  leftdrop2:
    number: L27
  leftdrop3:
    number: L28
  palacep:
    number: L31
  palacea1:
    number: L32
  palacel:
    number: L33
  palacea2:
    number: L34
  palacec:
    number: L35
  palacee:
    number: L36
  rightoutlane:
    number: L37
  rightinlane:
    number: L38
  special:
    number: L41
  clowntime:
    number: L42
  spotpalace:
    number: L43
  skillshot:
    number: L44
  hurricanevalue:
    number: L45
  hurricane1mil:
    number: L46
  hurricane2mil:
    number: L47
  hurricane3mil:
    number: L48
  lock2:
    number: L51
  lock1:
    number: L52
  mystery:
    number: L53
  jackpot:
    number: L54
  playitagain:
    number: L55
  quickscore:
    number: L56
  ferriswheel:
    number: L57
  million:
    number: L58
  comet50k:
    number: L61
  comet100k:
    number: L62
  comet200k:
    number: L63
  comet300k:
    number: L64
  leftpop:
    number: L65
  rightpop:
    number: L66
  bottompop:
    number: L67
  dunkthedummy:
    number: L68
  allscoresx2:
    number: L71
  allscoresx3:
    number: L72
  allscoresx5:
    number: L73
  palaceclock:
    number: L74
  rightstandup4:
    number: L75
  rightstandup3:
    number: L76
  rightstandup2:
    number: L77
  rightstandup1:
    number: L78
  juggler1:
    number: L81
  juggler2:
    number: L82
  juggler3:
    number: L83
  juggler4:
    number: L84
  flipperlanes:
    number: L85
  start:
    number: L86
  leftsling:
    number: L87
  rightslot:
    number: L88

ball_devices:
  outhole:
    tags: drain
    ball_switches: outhole
    eject_coil: outhole
    eject_targets: trough
    confirm_eject_type: target
    debug: true
  trough:
    tags: trough, home
    ball_switches: trough1, trough2, trough3
    eject_coil: ballRelease
    eject_targets: plunger
    confirm_eject_type: target
    debug: true
  plunger:
    tags: ball_add_live
    ball_switches: shooterLane
    mechanical_eject: true
    debug: true
    eject_timeouts: 4s
    ball_missing_timeouts: 1s
  leftjuggler:
    ball_switches: leftJuggler
    eject_coil: leftJuggler
    confirm_eject_type: target
    eject_targets: rightJuggler
    eject_timeouts: 3s
  rightjuggler:
    ball_switches: rightJuggler
    eject_coil: rightJuggler

autofire_coils:
  leftpop:
    coil: leftPop
    switch: leftPop
  rightpop:
    coil: rightPop
    switch: rightPop
  bottompop:
    coil: bottomPop
    switch: bottomPop
  leftslingshot:
    coil: leftSlingshot
    switch: leftSlingshot
  rightslingshot:
    coil: rightSlingshot
    switch: rightSlingshot

driver_enabled:
  ferris_wheel:
    number: c06
#    flippers:
#      number: gi08

drop_target_banks:
  leftbank:
    reset_coils: droptargetReset
    drop_targets: droptarget1, droptarget2, droptarget3
    reset_events:
      ball_starting: 0

drop_targets:
  droptarget1:
    switch: leftDrop1
  droptarget2:
    switch: leftDrop2
  droptarget3:
    switch: leftDrop3

#TargetGroups:
#    rightStandups:
#        targets: rightStandup1, rightStandup2, rightStandup3, rightStandup4
#        reset_events: targets_rightStandups_lit_complete
#        enable_events: ball_started
#        disable_events: ball_ending
#    extraBallLanes:
#        targets: leftOutlane, leftInlane, rightInlane, rightOutlane
#        rotate_left_events: sw_left_sling
#        rotate_right_events: sw_right_sling
#        reset_events: targets_extraBallLanes_lit_complete
#        enable_events: ball_started
#        disable_events: ball_ending
#
#Targets:
#    leftOutlane:
#        switch: leftOutlane
#        light: leftOutlane
#    leftInlane:
#        switch: leftInlane
#        light: leftInlane
#    rightInlane:
#        switch: rightInlane
#        light: rightInlane
#    rightOutlane:
#        switch: rightOutlane
#        light: rightOutlane
#    rightStandup1:
#        switch: rightStandup1
#        light: rightStandup1
#    rightStandup2:
#        switch: rightStandup2
#        light: rightStandup2
#    rightStandup3:
#        switch: rightStandup3
#        light: rightStandup3
#    rightStandup4:
#        switch: rightStandup4
#        light: rightStandup4

gis:
  backbox1:
    number: G01
    tags: gi
  backbox2:
    number: G02
    tags: gi
  playfield:
    number: G03
    tags: gi
  backbox3:
    number: G04
    tags: gi
  coindoor:
    number: G05
    tags: gi
  flipperenable:
    number: G08
    enable_events: ball_starting
    disable_events: ball_ending

physical_dmd:
  width: 128
  height: 32
  shades: 16
shots:
  rightstandup1:
    switch: rightStandup1
    light: rightStandup1
  rightstandup2:
    switch: rightStandup2
    light: rightStandup2
  rightstandup3:
    switch: rightStandup3
    light: rightStandup3
  rightstandup4:
    switch: rightStandup4
    light: rightStandup4

shot_groups:
  right_standups:
    shots: rightStandup1, rightStandup2, rightStandup3, rightStandup4



displays:
  dmd:
    width: 128
    height: 32
widget_styles:
  text_default:
    font_name: Quadrit
    font_size: 10
    crop_top: 2
    crop_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    crop_top: 3
    crop_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    crop_top: 2
    crop_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    crop_top: 1
    crop_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    crop_top: 2
    crop_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
#Shots:
#    slingshot:
#        Switch: leftSlingshot, rightSlingshot
#    dunkTheDummy:
#        Switch: dunkTheDummy
#    pop:
#        Switch: leftPop, rightPop, bottomPop
#    ferrisWheel:
#        Switch: ferrisWheel
#    hurricane:
#        Type: Sequence
#        Switches: hurricaneEntry, hurricaneExit
#        Time: 3s
#    comet:
#        Type: Sequence
#        Switches: cometEntry, cometExit
#        Time: 3s
#
#Scoring:
#    shot_slingshot:
#        Score: 4790
#    targets_extraBallLanes_unlit_hit:
#        Score: 7500
#    targets_extraBallLanes_lit_hit:
#        Score: 1000
#    shot_dunkTheDummy:
#        Score: 10000
#    shot_pop:
#        Score: 3050
#    shot_ferrisWheel:
#        Score: 20000
#    shot_comet:
#        Score: 75000
#    shot_hurricane:
#        Score: 100000
#    balldevice_leftJuggler_ball_enter:
#        Score: 38460
