#config_version=3

config:
  - window.yaml

hardware:
    Platform: fast
    DriverBoards: wpc

fast:
    ports: com4, com5, com6

modes:
  - base

coils:
    backboxMotor:
        number: C01
        allow_enable: True
    droptargetReset:
        number: C02
        pulse_ms: 30
    leftJuggler:
        number: C04
        pulse_ms: 18
    rightJuggler:
        number: C05
        pulse_ms: 20
#    ferrisWheels:
#        number: C06
#        allow_enable: True
    knocker:
        number: C07
        pulse_ms: 20
    outhole:
        number: C09
        pulse_ms: 20
    ballRelease:
        number: C10
        pulse_ms: 20
    leftSlingshot: 
        number: C11
        pulse_ms: 20
    rightSlingshot: 
        number: C12
        pulse_ms: 20
    leftPop:
        number: C13
        pulse_ms: 20
    rightPop:
        number: C14
        pulse_ms: 20
    bottomPop:
        number: C15
        pulse_ms: 20

switches:
    rightFlipper:
        number: S11
    leftFlipper:
        number: S12
    start:
        number: S13
        tags: start
    plumbBob:
        number: S14
        tags: tilt
    outhole:
        number: S15
    trough1:
        number: S16
    trough2:
        number: S17
    trough3:
        number: S18
    slamTilt:
        number: S21
        tags: slam_tilt
    coinDoorClosed:
        number: S22
    ticket:
        number: S23
        tags: playfield_active
    alwaysClosed:
        number: S24
        type: NC
    rightSlingshot:
        number: S25
        tags: playfield_active
    rightInlane:
        number: S26
        tags: playfield_active
    rightOutlane:
        number: S27
        tags: playfield_active
    shooterLane:
        number: S28
    ferrisWheel:
        number: S31
        tags:
    leftDrop1:
        number: S33
        tags: playfield_active
    leftDrop2:
        number: S34
        tags: playfield_active
    leftDrop3:
        number: S35
        tags: playfield_active
    leftSlingshot:
        number: S36
        tags: playfield_active
    leftInlane:
        number: S37
        tags: playfield_active
    leftOutlane:
        number: S38
        tags: playfield_active
    rightStandup1:
        number: S42
        tags: playfield_active
    rightStandup2:
        number: S43
        tags: playfield_active
    rightStandup3:
        number: S44
        tags: playfield_active
    rightStandup4:
        number: S45
        tags: playfield_active
    leftPop:
        number: S51
        tags: playfield_active
    rightPop:
        number: S52
        tags: playfield_active
    bottomPop:
        number: S53
        tags: playfield_active
    dunkTheDummy:
        number: S55
        tags: playfield_active
    leftJuggler:
        number: S56
    rightJuggler:
        number: S57
    hurricaneEntry:
        number: S61
        tags: playfield_active
    hurricaneExit:
        number: S62
        tags: playfield_active
    cometEntry:
        number: S63
        tags: playfield_active
    cometExit:
        number: S64
        tags: playfield_active
    coin1:
        number: SD1
    coin2:
        number: SD2
    coin3:
        number: SD3
    coin4:
        number: SD4
    esc:
        number: SD5
    down:
        number: SD6
    up:
        number: SD7
    enter:
        number: SD8

matrix_lights:
    clownLeftEye:
        number: L11
    clownRightEye:
        number: L12
    clownLeftCheek:
        number: L13
    clownNose:
        number: L14
    clownRightCheek:
        number: L15
    clownMouth:
        number: L16
    leftOutlane:
        number: L17
    leftInlane:
        number: L18
    bonus2x:
        number: L21
    bonus3x:
        number: L22
    bonus4x:
        number: L23
    bonus5x:
        number: L24
    bonus6x:
        number: L25
    leftDrop1:
        number: L26
    leftDrop2:
        number: L27
    leftDrop3:
        number: L28
    palaceP:
        number: L31
    palaceA1:
        number: L32
    palaceL:
        number: L33
    palaceA2:
        number: L34
    palaceC:
        number: L35
    palaceE:
        number: L36
    rightOutlane:
        number: L37
    rightInlane:
        number: L38
    special:
        number: L41
    clownTime:
        number: L42
    spotPalace:
        number: L43
    skillShot:
        number: L44
    hurricaneValue:
        number: L45
    hurricane1mil:
        number: L46
    hurricane2mil:
        number: L47
    hurricane3mil:
        number: L48
    lock2:
        number: L51
    lock1:
        number: L52
    mystery:
        number: L53
    jackpot:
        number: L54
    playItAgain:
        number: L55
    quickScore:
        number: L56
    ferrisWheel:
        number: L57
    million:
        number: L58
    comet50k:
        number: L61
    comet100k:
        number: L62
    comet200k:
        number: L63
    comet300k:
        number: L64
    leftPop:
        number: L65
    rightPop:
        number: L66
    bottomPop:
        number: L67
    dunkTheDummy:
        number: L68
    allScoresX2:
        number: L71
    allScoresX3:
        number: L72
    allScoresX5:
        number: L73
    palaceClock:
        number: L74
    rightStandup4:
        number: L75
    rightStandup3:
        number: L76
    rightStandup2:
        number: L77
    rightStandup1:
        number: L78
    juggler1:
        number: L81
    juggler2:
        number: L82
    juggler3:
        number: L83
    juggler4:
        number: L84
    flipperLanes:
        number: L85
    start:
        number: L86
    leftSling:
        number: L87
    rightSlot:
        number: L88

ball_devices:
    outhole:
        tags: drain
        ball_switches: outhole
        eject_coil: outhole
        eject_targets: trough
        confirm_eject_type: target
        debug: true
    trough:
        tags: trough, home
        ball_switches: trough1, trough2, trough3
        eject_coil: ballRelease
        eject_targets: plunger
        confirm_eject_type: target
        debug: true
    plunger:
        tags: ball_add_live
        ball_switches: shooterLane
        mechanical_eject: true
        debug: true
        eject_timeouts: 4s
        ball_missing_timeouts: 1s
    leftJuggler:
        ball_switches: leftJuggler
        eject_coil: leftJuggler
        confirm_eject_type: target
        eject_targets: rightJuggler
        eject_timeouts: 3s
    rightJuggler:
        ball_switches: rightJuggler
        eject_coil: rightJuggler

autofire_coils:
    leftPop:
        coil: leftPop
        switch: leftPop
    rightPop:
        coil: rightPop
        switch: rightPop
    bottomPop:
        coil: bottomPop
        switch: bottomPop
    leftSlingshot:
        coil: leftSlingshot
        switch: leftSlingshot
    rightSlingshot:
        coil: rightSlingshot
        switch: rightSlingshot

driver_enabled:
    ferris_wheel:
      number: c06
#    flippers:
#      number: gi08

drop_target_banks:
    leftBank:
        reset_coils: droptargetReset
        drop_targets: droptarget1, droptarget2, droptarget3
        reset_events:
            ball_starting: 0

drop_targets:
    droptarget1:
        switch: leftDrop1
    droptarget2:
        switch: leftDrop2
    droptarget3:
        switch: leftDrop3

#TargetGroups:
#    rightStandups:
#        targets: rightStandup1, rightStandup2, rightStandup3, rightStandup4
#        reset_events: targets_rightStandups_lit_complete
#        enable_events: ball_started
#        disable_events: ball_ending
#    extraBallLanes:
#        targets: leftOutlane, leftInlane, rightInlane, rightOutlane
#        rotate_left_events: sw_left_sling
#        rotate_right_events: sw_right_sling
#        reset_events: targets_extraBallLanes_lit_complete
#        enable_events: ball_started
#        disable_events: ball_ending
#
#Targets:
#    leftOutlane:
#        switch: leftOutlane
#        light: leftOutlane
#    leftInlane:
#        switch: leftInlane
#        light: leftInlane
#    rightInlane:
#        switch: rightInlane
#        light: rightInlane
#    rightOutlane:
#        switch: rightOutlane
#        light: rightOutlane
#    rightStandup1:
#        switch: rightStandup1
#        light: rightStandup1
#    rightStandup2:
#        switch: rightStandup2
#        light: rightStandup2
#    rightStandup3:
#        switch: rightStandup3
#        light: rightStandup3
#    rightStandup4:
#        switch: rightStandup4
#        light: rightStandup4

GIs:
    backbox1:
        number: G01
        tags: gi
    backbox2:
        number: G02
        tags: gi
    playfield:
        number: G03
        tags: gi
    backbox3:
        number: G04
        tags: gi
    coinDoor:
        number: G05
        tags: gi
    flipperEnable:
        number: G08
        enable_events: ball_starting
        disable_events: ball_ending

dmd:
    physical: yes
    width: 128
    height: 32
    shades: 16
    fps: auto

shots:
    rightStandup1:
        switch: rightStandup1
        light: rightStandup1
    rightStandup2:
        switch: rightStandup2
        light: rightStandup2
    rightStandup3:
        switch: rightStandup3
        light: rightStandup3
    rightStandup4:
        switch: rightStandup4
        light: rightStandup4

shot_groups:
  right_standups:
    shots: rightStandup1, rightStandup2, rightStandup3, rightStandup4



#Shots:
#    slingshot:
#        Switch: leftSlingshot, rightSlingshot
#    dunkTheDummy:
#        Switch: dunkTheDummy
#    pop:
#        Switch: leftPop, rightPop, bottomPop
#    ferrisWheel:
#        Switch: ferrisWheel
#    hurricane:
#        Type: Sequence
#        Switches: hurricaneEntry, hurricaneExit
#        Time: 3s
#    comet:
#        Type: Sequence
#        Switches: cometEntry, cometExit
#        Time: 3s
#
#Scoring:
#    shot_slingshot:
#        Score: 4790
#    targets_extraBallLanes_unlit_hit:
#        Score: 7500
#    targets_extraBallLanes_lit_hit:
#        Score: 1000
#    shot_dunkTheDummy:
#        Score: 10000
#    shot_pop:
#        Score: 3050
#    shot_ferrisWheel:
#        Score: 20000
#    shot_comet:
#        Score: 75000
#    shot_hurricane:
#        Score: 100000
#    balldevice_leftJuggler_ball_enter:
#        Score: 38460