#config_version=4

window:
  width: 600
  height: 200
  title: Mission Pinball Framework - Hurricane
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
displays:
  window:
    height: 200
    width: 600
slides:
  window_slide_1:
  - type: dmd
    width: 512
    height: 128
    pixel_color: ff5500
    dark_color: 220000
    z: 1
  - type: text
    style: tall title
    text: MISSION PINBALL FRAMEWORK
    anchor_y: top
    y: top-3
    font_size: 30
    z: 1
    color: white

  - type: rectangle
    width: 514
    height: 130
    z: 2
    color: 444444

  - type: text
    style: tall title
    text: STARTER GAME
    anchor_x: right
    anchor_y: bottom
    y: bottom+3
    x: right-42
    font_size: 30
    z: 1
    color: red
slide_player:
  machine_reset_phase_3:
    window_slide_1:
      target: window
