Mode:
    start_events: ball_starting
    stop_events: ball_ending
    priority: 100
    code: base.Base

SlidePlayer:
    mode_base_started:
      - type: Text
        text: "Pull Trigger To Begin"
        number_grouping: true
        double_zeros: true
        v_pos: center
        transition:
            type: move_in
            direction: top
      - type: Text
        text: PLAYER %number%
        v_pos: bottom
        h_pos: left
        font: small
      - type: Text
        text: BALL %ball%
        v_pos: bottom
        h_pos: right
        font: small
    ball_started:
        text: PLAYER %player BALL %ball
    player_score:
      - type: Text
        text: "%value"
        number_grouping: true
        v_pos: center
      - type: Text
        text: PLAYER %number%
        v_pos: bottom
        h_pos: left
        font: small
      - type: Text
        text: BALL %ball%
        v_pos: bottom
        h_pos: right
        font: small