#config_version=4

mode:
    start_events: ball_starting
    priority: 100

slide_player:
    mode_base_started:
      widgets:
      - type: text
        text: "Pull Trigger To Begin"
        number_grouping: true
        min_digits: 2
        y: center
      - type: text
        text: PLAYER %number%
        y: bottom
        x: left
        style: small
      - type: text
        text: BALL (ball)
        y: bottom
        x: right
        style: small
#      transition:
#          type: move_in
#          direction: top
    ball_started:
      widgets:
      - type: text
        text: PLAYER (player) BALL (ball)
    player_score:
      widgets:
      - type: text
        text: (score)
        number_grouping: true
      - type: text
        text: PLAYER (number)
        y: bottom
        x: left
        style: small
      - type: text
        text: BALL (ball)
        y: bottom
        x: right
        style: small

scoring:
  targets_all_targets_lit_complete:
    score: 1000000
  ball_started:
    score: 10