# config_version=4
mode:
  start_events: ball_ending
  stop_events: bonus_complete
  priority: 500
#  code: bonus.Bonus
  use_wait_queue: true


scoring:
  bonusvalue:
    score: 1000
  secondtolastbonusvalue:
    score: 2000
  lastbonusvalue:
    score: 3000
