#config_version=5

# Config file for Step 4 of our step-by-step tutorial.

# WARNING: The switch and coil numbers in this configuration file are for a Demolition Man machine.
# Do not use this file with your own hardware unless you change the coil and switch numbers to match your actual
# hardware!

switches:
    s_left_flipper:
        number: SF4
        tags: left_flipper
    s_right_flipper:
        number: SF2
        tags: right_flipper

coils:
    c_flipper_left_main:
        number: FLLM
        default_pulse_ms: 25
    c_flipper_left_hold:
        number: FLLH
        allow_enable: true
    c_flipper_right_main:
        number: FLRM
        default_pulse_ms: 25
    c_flipper_right_hold:
        number: FLRH
        allow_enable: yes

playfields:
    playfield:
        tags: default
        default_source_device: None

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3
