Mode:
    start_events: start_mode_battle_simulation
    stop_events: sw_end_mission, ball_ending #the sw_end_mission switch is just for testing
    code: battle_simulation.BattleSimulation
    priority: 500

Slide_Player:
    mode_battle_simulation_started:
      - type: Text
        text: "Battle Simulation!"
        number_grouping: true
        double_zeros: true
        v_pos: center
        transition:
            type: move_in
            direction: top
