#config_version=4

tilt:
  tilt_warning_switch_tag: tilt_warning
  tilt_switch_tag: tilt
  slam_tilt_switch_tag: slam_tilt
  warnings_to_tilt: 3
  reset_warnings_events: ball_ended
  multiple_hit_window: 300ms
  settle_time: 5s
  tilt_warnings_player_var: tilt_warnings

slide_player:
  tilt_warning_1: slide_20
  tilt_warning_2: slide_21
  tilt: slide_22
  tilt_clear: slide_23
slides:
  slide_20:
  - type: text
    text: WARNING
  slide_21:
  - type: text
    text: WARNING
    y: top-2
    anchor_y: top
  - type: text
    text: WARNING
    y: top-18
    anchor_y: top
  slide_22:
  - type: text
    text: TILT
  slide_23: []
