# config_version=4

machine:
  hz: 30
  balls installed: 1
  min balls: 0
  max balls: 1

game:
  balls per game: 3
  max players per game: 4

modes:
- base

scriptlets: attract.Attract

switches:
  s_start:
    number: 0
    tags: start
  s_flipper_left:
    number: 1
  s_flipper_right:
    number: 2
  s_tilt:
    number: 3
  s_trough:
    number: 4
  s_target_20:
    number: 8
  s_target_1:
    number: 9
  s_target_18:
    number: a
  s_target_2:
    number: b
  s_target_17:
    number: c
  s_pop_left:
    number: d
  s_rubber_upper_left:
    number: e
  s_orbit_left:
    number: f
  s_spinner:
    number: 10
  s_sling_left:
    number: 11
  s_sling_right:
    number: 12
  s_outlane_left:
    number: 13
  s_inlane_left:
    number: 14
  s_inlane_right:
    number: 15
  s_outlane_right:
    number: 16
  s_target_5:
    number: 18
  s_target_12:
    number: 19
  s_target_9:
    number: 1a
  s_target_3:
    number: 1c
  s_target_19:
    number: 1b
  s_pop_right:
    number: 1d
  s_mid_right_rubber:
    number: 1e
  s_pop_bumper_right_rubber:
    number: 1f
  s_lane_d:
    number: 20
  s_lane_a:
    number: 21
  s_lane_r:
    number: 22
  s_lane_t:
    number: 23
  s_lock_left:
    number: 24
  s_lock_center:
    number: 25
  s_lock_right:
    number: 26
  s_rubber_way_up_right:
    number: 27

coils:
  c_flipper_left:
    number: 0
    pulse_ms: 30
  c_flipper_right:
    number: 1
    pulse_ms: 30
  c_trough:
    number: 2
    pulse_ms: 20
  c_sling_left:
    number: 3
    pulse_ms: 20
  c_sling_right:
    number: 4
    pulse_ms: 20
  c_pop_left:
    number: 5
    pulse_ms: 20
  c_pop_right:
    number: 6
    pulse_ms: 20
  c_lock_left:
    number: 8
    pulse_ms: 12
  c_lock_center:
    number: 9
    pulse_ms: 12
  c_lock_right:
    number: a
    pulse_ms: 12
#    c_knocker:
#        number: b  # not hooked up

leds:
    # Main center dart board
  l_board_20:
    number: 5e
    tags: board_red, red
  l_board_1:
    number: 5f
    tags: board_black
  l_board_18:
    number: 60
    tags: board_red, red
  l_board_4:
    number: 61
    tags: board_black
  l_board_13:
    number: 62
    tags: board_red, red
  l_board_6:
    number: 63
    tags: board_black
  l_board_10:
    number: 64
    tags: board_red, red
  l_board_15:
    number: 42
    tags: board_black
  l_board_2:
    number: 43
    tags: board_red, red
  l_board_17:
    number: 44
    tags: board_black
  l_board_3:
    number: 51
    tags: board_red, red
  l_board_19:
    number: 52
    tags: board_black
  l_board_7:
    number: 54
    tags: board_red, red
  l_board_16:
    number: 55
    tags: board_black
  l_board_8:
    number: 58
    tags: board_red, red
  l_board_11:
    number: 59
    tags: board_black
  l_board_14:
    number: 5a
    tags: board_red, red
  l_board_9:
    number: 5b
    tags: board_black
  l_board_12:
    number: 5c
    tags: board_red, red
  l_board_5:
    number: 5d
    tags: board_black
  l_board_50:
    number: 53
    tags: board_red, red


    # Small green 301 circle
  l_301_1:
    number: 50
    tags: green
  l_301_2:
    number: 45
    tags: green
  l_301_3:
    number: 46
    tags: green
    debug: true
  l_301_4:
    number: 47
    tags: green
  l_301_5:
    number: 48
    tags: green
  l_301_6:
    number: 4a
    tags: green
  l_301_7:
    number: 4c
    tags: green
  l_301_8:
    number: 4d
    tags: green
  l_301_9:
    number: 4e
    tags: green
  l_301_10:
    number: 4f
    tags: green


  l_left_extra_ball:
    number: 56
    tags: yellow
  l_right_extra_ball:
    number: 41
    tags: yellow
  l_left_special:
    number: 57
    tags: red
  l_right_special:
    number: 40
    tags: red
  l_center_special:
    number: 4b
    tags: red
  l_throw_again:
    number: 49
    tags: yellow

  l_orbit_2x:
    number: 13
    tags: yellow
  l_orbit_3x:
    number: 14
    tags: yellow

    # Clear number inserts
  l_white_1:
    number: 16
    tags: rgb
  l_white_2:
    number: d
    tags: rgb
  l_white_3:
    number: b
    tags: rgb
  l_white_4:
    number: 12
    tags: rgb
  l_white_5:
    number: 0
    tags: rgb
  l_white_6:
    number: f
    tags: rgb
  l_white_7:
    number: 7
    tags: rgb
  l_white_8:
    number: 4
    tags: rgb
  l_white_9:
    number: 2
    tags: rgb
  l_white_10:
    number: 10
    tags: rgb
  l_white_11:
    number: 5
    tags: rgb
  l_white_12:
    number: 1
    tags: rgb
  l_white_13:
    number: e
    tags: rgb
  l_white_14:
    number: 6
    tags: rgb
  l_white_15:
    number: 11
    tags: rgb
  l_white_16:
    number: 3
    tags: rgb
  l_white_17:
    number: c
    tags: rgb
  l_white_18:
    number: 15
    tags: rgb
  l_white_19:
    number: a
    tags: rgb
  l_white_20:
    number: 17
    tags: rgb

  l_2x:
    number: 9
    tags: yellow
  l_3x:
    number: 8
    tags: yellow

  l_lane_d:
    number: 18
    tags: green
  l_lane_a:
    number: 19
    tags: green
  l_lane_r:
    number: 1c
    tags: green
  l_lane_t:
    number: 1d
    tags: green

  l_bullseye:
    number: 1a
    tags: red
  l_win:
    number: 1b
    tags: green



        ### GI
  l_slingshot_left_1:
    number: c4
    tags: gi
  l_slingshot_left_2:
    number: c5
    tags: gi
  l_slingshot_right_1:
    number: c7
    tags: gi
  l_slingshot_right_2:
    number: c6
    tags: gi
  l_flipper_return_left_1:
    number: c3
    tags: gi
  l_flipper_return_left_2:
    number: c2
    tags: gi
  l_flipper_return_right_1:
    number: c9
    tags: gi
  l_flipper_return_right_2:
    number: c8
    tags: gi
  l_mid_plastic_left_1:
    number: 80
    tags: gi
  l_mid_plastic_left_2:
    number: 81
    tags: gi
  l_mid_plastic_left_3:
    number: 82
    tags: gi
  l_mid_plastic_right_1:
    number: 90
    tags: gi
  l_mid_plastic_right_2:
    number: 8F
    tags: gi
  l_mid_plastic_right_3:
    number: 8E
    tags: gi
  l_upper_plastic_left_1:
    number: 83
    tags: gi
    #l_upper_plastic_left_2:
    #    number:
    #    tags: gi
    #l_upper_plastic_left_3:
    #    number:
    #    tags: gi
  l_upper_plastic_right_1:
    number: 8D
    tags: gi
  l_upper_plastic_right_2:
    number: 8C
    tags: gi
    #l_upper_plastic_right_3:
    #    number:
    #    tags: gi
    #l_upper_plastic_right_4:
    #    number:
    #    tags: gi
  l_lane_divider_1:
    number: 84
    tags: gi
  l_lane_divider_2:
    number: 85
    tags: gi
  l_lane_divider_3:
    number: 86
    tags: gi
  l_lane_divider_4:
    number: 89
    tags: gi
  l_lane_divider_5:
    number: 8A
    tags: gi
  l_lane_divider_6:
    number: 8B
    tags: gi
  l_upper_center_plastic_1:
    number: 87
    tags: gi
  l_upper_center_plastic_2:
    number: 88
    tags: gi


ball_devices:
  trough:
    tags: trough, home, drain, ball_add_live
    ball_switches: s_trough
    entrance_count_delay: 200ms
    exit_count_delay: 1s
    eject_coil: c_trough
    confirm_eject_type: count
  left_lock:
    ball_switches: s_lock_left
    eject_coil: c_lock_left
  center_lock:
    ball_switches: s_lock_center
    eject_coil: c_lock_center
  right_lock:
    ball_switches: s_lock_right
    eject_coil: c_lock_right

flippers:
  left:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left
  right:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right

autofire_coils:
  left_pop:
    coil: c_pop_left
    switch: s_pop_left
  right_pop:
    coil: c_pop_right
    switch: s_pop_right
  left_sling:
    coil: c_sling_left
    switch: s_sling_left
  right_sling:
    coil: c_sling_right
    switch: s_sling_right

targets:
  dart_d:
    switch: s_lane_d
    light: l_lane_d
  dart_a:
    switch: s_lane_a
    light: l_lane_a
  dart_r:
    switch: s_lane_r
    light: l_lane_r
  dart_t:
    switch: s_lane_t
    light_: l_lane_t
  standup_20:
    switch: s_target_20
    light: l_white_20
  standup_1:
    switch: s_target_1
    light: l_white_1
  standup_18:
    switch: s_target_18
    light: l_white_18
  standup_2:
    switch: s_target_2
    light: l_white_2
  standup_17:
    switch: s_target_17
    light: l_white_17
  standup_5:
    switch: s_target_5
    light: l_white_5
  standup_12:
    switch: s_target_12
    light: l_white_12
  standup_9:
    switch: s_target_9
    light: l_white_9
  standup_3:
    switch: s_target_3
    light: l_white_3
  standup_19:
    switch: s_target_19
    light: l_white_19

target_groups:
  all_targets:
    targets: standup_9, standup_12, standup_5, standup_20, standup_1, standup_18,
      standup_2, standup_17, standup_3, standup_19
    enable_events: ball_started
    reset_events: ball_ending, targets_all_targets_lit_complete
  rollovers:
    targets: dart_d, dart_a, dart_r, dart_t
    enable_events: ball_started
    reset_events: ball_ending, targets_rollovers_lit_complete


window:
  width: 1366
  height: 768
  title: Bullseye 301.1
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
keyboard:
  s:
    switch: s_start

bcp:
  connections:
    local_display:
      host: localhost
      port: 5050

images:
  backglass:
    file: 301.bmp

shots:
  left_orbit:
    type: sequence
    switches: s_orbit_left, s_lane_d
    time: 3s
  dart:
    switch: s_lane_d, s_lane_a, s_lane_r, s_lane_t
  inlane:
    switch: s_inlane_right, s_inlane_left
  outlane:
    switch: s_outlane_right, s_outlane_left

shows:
  flash:
  - time: 0
    leds:
      (leds): white
  - time: '+1'
    lights:
      (lights): 0

  - time: '+1'
scoring:
  targets_all_targets_lit_complete:
    score: 1000000
  ball_started:
    score: 10
displays:
  window:
    height: 768
    width: 1366
  dmd:
    width: 128
    height: 32
    shades: 16
    fps: auto
    default: true
slides:
  window_slide_1:
  - type: dmd
    width: 512
    height: 128
    anchor_y: bottom
    x: center-6
    pixel_color: ff6600
    dark_color: 220000
    z: 1
    y: bottom
  - type: text
    style: tall title
    text: FAST PINBALL
    anchor_x: right
    anchor_y: bottom
    y: bottom+10
    x: right-20
    font_size: 60
    z: 1
    color: red

  - type: image
    image: backglass
    x: center+0
    y: top+0
    anchor_y: top
    priority: 0

  - type: rectangle
    width: 518
    height: 134
    z: 2
    anchor_y: bottom
    color: ffbb00

    y: bottom
#light_player:
#
#    attract_start:
#      # - show: dart_board_spiral
#      #   repeat: yes
#      #   tocks_per_sec: 24
#      # - show: dart_board_alternate
#      #   repeat: yes
#      #   tocks_per_sec: 4
#      #   num_repeats: 10
#      - show: green_301_ring_spin
#        repeat: yes
#        tocks_per_sec: 10
#      - show: rainbow_circle_spinners
#        repeat: yes
#        tocks_per_sec: 15
#      - show: gi_on
#        repeat: yes
#        tocks_per_sec: 1
#
#    attract_stop:
#      - show: dart_board_alternate
#        action: stop
#      - show: green_301_ring_spin
#        action: stop
#      - show: rainbow_circle_spinners
#        action: stop

#light_player:
#    attract_start:
#        leds: l_301_3
#        script: flash
#        tocks_per_sec: 1
#        repeat: yes

slide_player:
  machine_reset_phase_3:
    window_slide_1:
      target: window
widget_styles:
  text_default:
    font_name: Quadrit
    font_size: 10
    crop_top: 2
    crop_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    crop_top: 3
    crop_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    crop_top: 2
    crop_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    crop_top: 1
    crop_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    crop_top: 2
    crop_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
show_player:
  attract_start:
    attract_display:
      loops: -1
      speed: 1
  attract_stop:
    attract_display:
      action: stop

