# config_version=2

hardware:
    Platform: fast
    DriverBoards: fast

fast:
    ports: com3, com4, com5
    #ports: /dev/ttyUSB0, /dev/ttyUSB1, /dev/ttyUSB2
    config_number_format: hex
    default_debounce_close: 10ms
    default_debounce_open: 30ms

Config:
    - config.yaml
