# config_version=4
# Pinbot

system11:
  ac_relay_driver_number: c14

mpf:
  default_pulse_ms: 30

#switches:
#  # Cabinet
#    left_coin:
#        number: S16
#        label: 'Left Coin Slot'
#    center_coin:
#        number: S15
#        label: 'Center Coin Slot'
#    right_coin:
#        number: S14
#        label: 'Right Coin Slot'
#    up:
#        number: SD8
#    down:
#        number: SD2
#    enter:
#        number: SD5
#    exit:
#        number: SD0
#    start:
#        number: S13
#        label: 'Start Button'
#        tags: start
#    plumb_bob:
#        number: S11
#        label: 'Tilt'
#        tags: tilt_warning
#    roll_tilt:
#        number: S12
#        label: 'Roll Tilt'
#        tags: tilt
#    slam_tilt:
#        number: S17
#        label: 'Slam Tilt'
#        tags: slam_tilt
#    high_score_reset:
#        number: S18
#    playfield_tilt:
#        number: S21
#        label: 'Playfield Tilt'
#
## Lower playfield
#    left_flipper_eos:
#        number: S22
#        label: 'Left Flipper EOS'
#    right_flipper_eos:
#        number: S23
#        label: 'Right Flipper EOS'
#    left_outlane:
#        number: S24
#        label: 'Left Outlane'
#        tags: playfield_active
#    left_inlane:
#        number: S25
#        label: 'Left Inlane'
#        tags: playfield_active
#    right_inlane:
#        number: S26
#        label: 'Right Inlane'
#        tags: playfield_active
#    right_outlane:
#        number: S27
#        label: 'Right Outlane'
#        tags: playfield_active
#    outhole:
#        number: S28
#        tags: outhole
#        label: 'Outhole'
#    trough2:
#        number: S32
#        tags: trough
#        label: 'Rightmost Ball Trough minus 1'
#    trough1:
#        number: S31
#        tags: trough
#        label: 'Rightmost Ball Trough'
#    plunger_lane:
#        number: S34
#        tags:
#        label: 'Plunger Lane'
#    left_sling:
#        number: S76
#        label: 'Left Sling'
#        tags: playfield_active
#    right_sling:
#        number: S77
#        label: 'Right Sling'
#        tags: playfield_active
#
#  # Vortex
#    vortex_5k:
#        number: S38
#        tags: playfield_active
#    vortex_20k:
#        number: S36
#        tags: playfield_active
#    vortex_100k:
#        number: S37
#        tags: playfield_active
#
## Chest & Visor
#    chext_matrix_01:
#        number: S44
#        label: 'Chest Horiz Yellow'
#        tags: playfield_active
#    chext_matrix_02:
#        number: S45
#        label: 'Chest Horiz Blue'
#        tags: playfield_active
#    chext_matrix_03:
#        number: S46
#        label: 'Chest Horiz Orange'
#        tags: playfield_active
#    chext_matrix_04:
#        number: S47
#        label: 'Chest Horiz Green'
#        tags: playfield_active
#    chext_matrix_05:
#        number: S48
#        label: 'Chest Horiz Red'
#        tags: playfield_active
#    chext_matrix_10:
#        number: S51
#        label: 'Chest Vert Yellow'
#        tags: playfield_active
#    chext_matrix_20:
#        number: S52
#        label: 'Chest Vert Blue'
#        tags: playfield_active
#    chext_matrix_30:
#        number: S53
#        label: 'Chest Vert Orange'
#        tags: playfield_active
#    chext_matrix_40:
#        number: S54
#        label: 'Chest Vert Green'
#        tags: playfield_active
#    chext_matrix_50:
#        number: S55
#        label: 'Chest Vert Red'
#        tags: playfield_active
#    visor_open:
#        number: S67
#    visor_closed:
#        number: S66
##EJECTS/EYEBALLS
#    right_eyeball:
#        number: S42
#        label: 'Right Eye Eject'
#        tags: playfield_active
#    left_eyeball:
#        number: S41
#        label: 'Left Eye Eject'
#        tags: playfield_active
#    single_eject:
#        number: S56
#        label: 'Single Eject'
#        tags: playfield_active
#
## RAMP SWITCHES
#    ramp_exit:
#        number: S57
#        tags: playfield_active
#    ramp_enter:
#        number: S58
#        tags: playfield_active
#    ramp_down:
#        number: S64
#        tags: playfield_active
#
## Pop bumpers
#    top_pop_bumper:
#        number: S74
#        label: 'Top Jet Bumper'
#        tags: playfield_active
#    middle_pop_bumper:
#        number: S68
#        label: 'Middle Jet Bumper'
#        tags: playfield_active
#    bottom_pop_bumper:
#        number: S75
#        label: 'Lower Jet Bumper'
#        tags: playfield_active
#
## 10 POINTER SWITCHES
#    ten_pointer_1:
#        number: S78
#        tags: playfield_active
#    ten_Pointer_2_BehindDropBank:
#        tags: playfield_active
#        number: S83
#    ten_Pointer_3:
#        number: S84
#        tags: playfield_active
#
## DROP TARGET BANK
#    upper_Drop:
#        number: S71
#        tags: playfield_active
#    mid_Drop:
#        number: S72
#        tags: playfield_active
#    lower_Drop:
#        number: S73
#        tags: playfield_active
###################################
## STANDUP TARGETS
#    Energy_StandUp:
#        number: S65
#        tags: playfield_active
#    advance_Planet:
#        number: S33
#        tags: playfield_active
###################################
## UNUSED SWITCHES
#    debug:
#        number: S35
#    diag_LED:
#        number: S61
#    unused_62:
#        number: S62
#    unused_63:
#        number: S63
#    unused_81:
#        number: S81
#    exit:
#        number: S82
#    up:
#        number: S85
#    down:
#        number: S86
#    enter:
#        number: S43
#    NA1:
#        number: S88

coils:
  outhole:
    number: c01a
  knocker:
    number: c01c
  trough:
    number: c02a
  single_eject_hole:
    number: c03a
  drop_target_reset:
    number: c04a
  ramp_raise:
    number: c05a
  ramp_lower:
    number: c06a
  left_eye:
    number: c07a
  right_eye:
    number: c08a
  visor_motor:
    number: c13
#  ac_select:
#    number: c14

  # Special solenoids
  pop_bumper_bottom:
    number: c17
  pop_bumper_left:
    number: c19
  left_kicker:
    number: c20
  right_sling:
    number: c22

flashers:
  upper_pf_and_topper_1:
    number: c02c
  left_insert_bottom:
    number: c03c
  right_insert_bottom:
    number: c04c
  lower_pf_and_topper_2:
    number: c05c
  energy:
    number: c06c
  left_playfield:
    number: c07c
  sun:
    number: c08c
  robot_face_insert_bottom:
    number: c09

  topper_3:
    number: c15
  topper_4:
    number: c16

matrix_lights:
  gameoverbackbox:
    number: L11
  matchbackbox:
    number: L12
  ballinplaybackbox:
    number: L13
  mouth1leftbackbox:
    number: L14
  mouth2backbox:
    number: L15
  mouth3backbox:
    number: L16
  mouth4backbox:
    number: L17
  mouth5rightbackbox:
    number: L18
  x2bonus:
    number: L21
  x3bonus:
    number: L22
  x4bonus:
    number: L23
  x5bonus:
    number: L24
  eject25k:
    number: L25
  eject50k:
    number: L26
  eject75k:
    number: L27
  ejectlightextraball:
    number: L28
  droptargettimerlamp:
    number: L31
  advanceplanent:
    number: L32
  pluto:
    number: L33
  neptune:
    number: L34
  uranus:
    number: L35
  saturn:
    number: L36
  jupiter:
    number: L37
  mars:
    number: L38
  earth:
    number: L41
  venus:
    number: L42
  mercury:
    number: L43
  chestmatrix11:
    number: L44
  chestmatrix21:
    number: L45
  chestmatrix31:
    number: L46
  chestmatrix41:
    number: L47
  chestmatrix51:
    number: L48
  shootagain:
    number: L51
  scoreenergy:
    number: L52
  solarenergyvalue:
    number: L53
  chestmatrix12:
    number: L54
  chestmatrix22:
    number: L55
  chestmatrix32:
    number: L56
  chestmatrix42:
    number: L57
  chestmatrix52:
    number: L58
  droptarget1top:
    number: L61
  droptarget2middle:
    number: L62
  droptarget3bottom:
    number: L63
  chestmatrix13:
    number: L64
  chestmatrix23:
    number: L65
  chestmatrix33:
    number: L66
  chestmatrix43:
    number: L67
  chestmatrix53:
    number: L68
  leftoutlaneextraball:
    number: L71
  leftinlaneextraball:
    number: L72
  speciallamp:
    number: L73
  chestmatrix14:
    number: L74
  chestmatrix24:
    number: L75
  chestmatrix34:
    number: L76
  chestmatrix44:
    number: L77
  chestmatrix54:
    number: L78
  rightoutlaneextraball:
    number: L81
  rightinlaneextraball:
    number: L82
  notusedlamp83:
    number: L83
  chestmatrix15:
    number: L84
  chestmatrix25:
    number: L85
  chestmatrix35:
    number: L86
  chestmatrix45:
    number: L87
  chestmatrix55:
    number: L88

#gis:
#  robot_visor:
#    number: c10
#  insert_bottom:
#    number: c11
#  playfield:
#    number: c12
#  left_visor:
#    number: c18

driver_enabled:
  playfield_devices:
    number: c23

#ball_devices:
#    outhole:
#        ball_switches: outhole
#        eject_coil: outhole
#        confirm_eject_type: target
#        eject_targets: trough
#        tags: drain
#        debug: yes
#    trough:
#        ball_switches: trough1, trough2
#        eject_coil: trough
#        eject_targets: plunger_lane
#        tags: home
#        debug: yes
#    plunger_lane:
#        ball_switches:  plunger_lane
#        mechanical_eject: true
#        tags: home, ball_add_live
#        debug: yes
#    eject_hole:
#        ball_switches: single_eject
#        eject_coil: single_eject_hole
#    left_eye:
#        ball_switches: left_eyeball
#        eject_coil: left_eye
#    right_eye:
#        ball_switches: right_eyeball
#        eject_coil: right_eye

bcp:
  local_display:
    host: 127.0.0.1
    port: 5050
