Mode:
    start_events: start_mode_asteroid_threat
    stop_events: sw_end_mission, ball_ending #the sw_end_mission switch is just for testing
    code: asteroid_threat.AsteroidThreat
    priority: 500

Slide_Player:
    mode_asteroid_threat_started:
      - type: Text
        text: "Oh No's! Asteroids!"
        number_grouping: true
        double_zeros: true
        v_pos: center
        transition:
            type: move_in
            direction: top
