#config_version=3

hardware:
  platform: p_roc
  driverboards: snux

#scriptlets:
#  jokerz.Jokerz

switches:
  c_enabled:
    number: s12
  start:
    number: s13

coils:
  outhole:
    number: c16
    pulse_ms: 30
  left_upf_jo_flasher:
    number: c01c


  flipper_enable:
    number: c23
  top_right_eject:
    number: c16



matrix_lights:
  bell_1:
    number: l54
  bell_2:
    number: l55
  bell_3:
    number: l56
  bell_4:
    number: l57
  bell_5:
    number: l58

driver_controlled:
  flippers:
    enable_coil_name: flipper_enable