#config_version=5

mode:
  start_events: start_mode_skillshot
  stop_events: stop_mode_skillshot, skillshot_hit
  priority: 1000

config:
  - skillshot_slides.yaml

event_player:
  playfield_active: stop_mode_skillshot|3s

random_event_player:
  mode_skillshot_started: 
    events:
      - advance_skillshot_left
      - advance_skillshot_middle
      - advance_skillshot_right

shot_groups:
  skillshot:
    shots: skillshot_left, skillshot_middle, skillshot_right
    disable_rotation_events: s_plunger_lane_inactive
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active

shots:
  skillshot_left:
    advance_events: advance_skillshot_left
    switch: s_lane_left
    show_tokens:
      led: l_lane_left
  skillshot_middle:
    advance_events: advance_skillshot_middle
    switch: s_lane_middle
    show_tokens:
      led: l_lane_middle
  skillshot_right:
    advance_events: advance_skillshot_right
    switch: s_lane_right
    show_tokens:
      led: l_lane_right

shot_profiles:
  skillshot_profile:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: lit
        show: flashing

variable_player:
  skillshot_lit_hit:
    score: 20_000
    