#config_version=6

widget_player:
  mode_skillshot_started:
    skillshot_widget:
      action: add
      slide: base_slide
  mode_skillshot_stopped:
    skillshot_widget:
      action: remove
      slide: base_slide

widgets:
  skillshot_widget:
    - type: ellipse
      opacity: 0.5
      width: 20
      height: 20
      y: 20
      x: 260
      animations:
        add_to_slide{current_player.shot_skillshot_left==1}: shot_flashing
        player_shot_skillshot_left{value==0}: shot_off
        player_shot_skillshot_left{value==1}: shot_flashing
    - type: ellipse
      opacity: 0.5
      width: 20
      height: 20
      y: 20
      x: 320
      animations:
        add_to_slide{current_player.shot_skillshot_middle==1}: shot_flashing
        player_shot_skillshot_middle{value==0}: shot_off
        player_shot_skillshot_middle{value==1}: shot_flashing
    - type: ellipse
      opacity: 0.5
      width: 20
      height: 20
      y: 20
      x: 380
      animations:
        add_to_slide{current_player.shot_skillshot_right==1}: shot_flashing
        player_shot_skillshot_right{value==0}: shot_off
        player_shot_skillshot_right{value==1}: shot_flashing
