Mode:
    start_events: start_mode_search_the_galaxy
    stop_events: sw_end_mission, ball_ending #the sw_end_mission switch is just for testing
    code: search_the_galaxy.SearchTheGalaxy
    priority: 500

Slide_Player:
    mode_search_the_galaxy_started:
      - type: Text
        text: "Search the Galaxy"
        number_grouping: true
        double_zeros: true
        v_pos: center
        transition:
            type: move_in
            direction: top
