#config_version=4

show_player:
  mode_attract_started:
    attract_dmd_loop:
      loops: -1
      speed: 1
    palace_swoop:
      loops: -1
      speed: 10
  mode_attract_stopped:
    attract_dmd_loop:
      action: stop
    palace_swoop:
      action: stop

