#config_version=3

light_player:
  mode_attract_started:
    - show: palace_swoop
      repeat: yes
      tocks_per_sec: 10
  mode_attract_stopped:
    - show: palace_swoop
      action: stop

show_player:
  mode_attract_started:
    - show: attract_dmd_loop
      repeat: yes
      tocks_per_sec: 1
  mode_attract_stopped:
    - show: attract_dmd_loop
      action: stop