# config_version=4
mode:
  start_events: ball_starting
  priority: 100

scoring:
  shot_rightramp:
    score: 8000
  shot_leftramp:
    score: 7000
  shot_leftorbit:
    score: 6000
  shot_weakrightorbit:
    score: 11000
  shot_fullrightorbit:
    score: 6500
  shot_airraidramp:
    score: 10000
  shot_orangestandups:
    score: 2500
  shot_slingshot:
    score: 210
  shot_inlane:
    score: 1070
  shot_outlane:
    score: 930
  shot_droptarget:
    score: 1000
  drop_targets_judge_complete:
    score: 10000
  standups_pf_standups_complete:
    score: 5000

slide_player:
  player_score: slide_1
  tilt_hit: slide_2
  ball_live_added: slide_3
  mode_base_started:
    slide_4:
      transition:
        type: move_in
        direction: top
  balldevice_deadworld_ball_enter: slide_5
sound_player:
  waiting to plunge loop:
    sound: waiting to plunge loop
    start_events: mode_base_started
    stop_events: ball_live_added
    duration:
    loops: -1
    priority:
    fade_in: 0
    fade_out: 0
    volume: 1
  ball launch:
    sound: ball launch motorcycle
    start_events: balldevice_shooterLaneR_ball_eject_attempt
  sling:
    sound: slingshot
    start_events: shot_Slingshot

logic_blocks:
  accruals:
    both_ramps_made:
      events: shot_RightRamp, shot_LeftRamp
      events_when_complete: both_ramps_made
      disable_events: both_ramps_made
  counters:
    total_ramps:
      count_events: shot_RightRamp, shot_LeftRamp
slides:
  slide_1:
  - type: text
    text: '%value'
    number_grouping: true
  - type: text
    text: (PLAYER) (number)
    anchor_y: bottom
    anchor_x: left
    style: small
    y: bottom
    x: left
  - type: text
    text: (BALL) (ball)
    anchor_y: bottom
    anchor_x: right
    style: small
    y: bottom
    x: right
  slide_2:
  - type: text
    text: WARNING
  slide_3:
  - type: text
    text: LET'S GO!
    time: 2s
  slide_4:
  - type: text
    text: (score)
    number_grouping: true
    min_digits: 2
  - type: text
    text: (PLAYER) (number)
    anchor_y: bottom
    anchor_x: left
    style: small
    y: bottom
    x: left
  - type: text
    text: (BALL) (ball)
    anchor_y: bottom
    anchor_x: right
    style: small
    y: bottom
    x: right
  slide_5:
  - type: text
    text: 'BALLS LOCKED: %balls'
show_player:
  mode_base_started:
    game_info:
      loops: -1
      speed: 1         

