# config_version=4

machine:
  balls_installed: 1 

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: com4, com5, com6
  config_number_format: hex

open_pixel_control:
  number_format: hex

modes:
- base

led_settings:
  brightness_compensation: 0.1

switches:
  leftpop:
    number: 2c
  rightpop:
    number: 2b
  bottompop:
    number: 2d
  leftoutlane:
    number: b
  rightoutlane:
    number: c
  leftinlane:
    number: d
  rightinlane:
    number: e
  leftflipper:
    number: 0
    tags: left_flipper
    debounce_close: 2
  rightflipper:
    number: 2
    tags: right_flipper
    debounce_close: 2
  start:
    tags: start
    number: 3
  rightsling:
    number: 4
  leftsling:
    number: 1
  balllock:
    number: 6
  trough:
    number: 7
  toplaneleft:
    number: 20
  toplanemiddle:
    number: 21
  toplaneright:
    number: 22
  spinner:
    number: 23
  leftorbit:
    number: 24
  standuptopleft:
    number: 25
  standupmidleft2:
    number: 26
  standupmidleft1:
    number: 27
  standupmiddle:
    number: 28
  standupmidright2:
    number: 29
  standupmidright1:
    number: 2a  

coils:
  leftpop:
    number: 8
    pulse_ms: 20
  rightpop:
    number: 9
    pulse_ms: 20
  bottompop:
    number: 10
    pulse_ms: 20
  leftflippermain:
    number: 0
    pulse_ms: 30
  leftflipperhold:
    number: 1
  rightflippermain:
    number: 2
    pulse_ms: 30
  rightflipperhold:
    number: 3
  rightsling:
    number: 4
    pulse_ms: 9
  leftsling:
    number: 5
    pulse_ms: 9
  balllock:
    number: 6
    pulse_ms: 20
  trough:
    number: 7
    pulse_ms: 40  

leds:
  leftorbit:
    number: 0
  leftupperstandup:
    number: 1
    tags: standup
  upperlaneleft:
    number: 2
  upperrolloverleft:
    number: 3
  upperlanemiddle:
    number: 4
  upperrollovermiddle:
    number: 5
  upperlaneright:
    number: 6
  upperrolloverright:
    number: 7
  locklanetop:
    number: 8
  locklane1:
    number: 9
  locklane2:
    number: a
  locklane3:
    number: b
  locklane4:
    number: c
  locklane5:
    number: d
  semicircle10:
    number: e
  righttarget1:
    number: f
    tags: standup
  righttarget2:
    number: 10
    tags: standup
  centerrow5:
    number: 11
  centerrow4:
    number: 12
  centerrow3:
    number: 13
  centerrowred:
    number: 14
  centerrow2:
    number: 15
  centerrow1:
    number: 16
  spinnerarrow:
    number: 17
  lefttarget2:
    number: 18
    tags: standup
  lefttarget1:
    number: 19
    tags: standup
  leftoutlane:
    number: 1a
  semicircle1:
    number: 1b
  semicircle2:
    number: 1c
  semicircle3:
    number: 1d
  semicircle4:
    number: 1e
  semicircle5:
    number: 1f
  shootagain:
    number: 20
  semicircle_above:
    number: 21
  semicircle6:
    number: 22
  semicircle7:
    number: 23
  semicircle8:
    number: 24
  semicircle9:
    number: 25
  rightoutlane:
    number: 26  

ball_devices:
  trough:
    tags: trough, home, drain, ball_add_live
    ball_switches: trough
    entrance_count_delay: 200ms
    exit_count_delay: 1s
    eject_coil: trough
    confirm_eject_type: count

  balllock:
    ball_switches: ballLock
    entrance_count_delay: 200ms
    exit_count_delay: 1s
    eject_coil: ballLock
    confirm_eject_type: count

flippers:
  left:
    main_coil: leftFlipperMain
    hold_coil: leftFlipperHold
    activation_switch: leftFlipper
  right:
    main_coil: rightFlipperMain
    hold_coil: rightFlipperHold
    activation_switch: rightFlipper

autofire_coils:
  leftpop:
    coil: leftPop
    switch: leftPop
  rightpop:
    coil: rightPop
    switch: rightPop
  bottompop:
    coil: bottomPop
    switch: bottomPop
  leftsling:
    coil: leftSling
    switch: leftSling
  rightsling:
    coil: rightSling
    switch: rightSling

shots:
  laneleft:
    switch: topLaneLeft
    led: upperLaneLeft
  lanemiddle:
    switch: topLaneMiddle
    led: upperLaneMiddle
  laneright:
    switch: topLaneRight
    led: upperLaneRight
  left1:
    led: lefttarget1
    switch: standupMidLeft1
  left2:
    led: lefttarget2
    switch: standupMidLeft2
  right1:
    led: righttarget1
    switch: standupMidRight1
  right2:
    led: righttarget2
    switch: standupMidRight2
  middle:
    led: centerRowRed
    switch: standupMiddle
  upperleft:
    switch: standupTopLeft
    led: leftUpperStandup
  spinner:
    led: spinnerArrow
    switch: spinner
    reset_events:
      shot_spinner_unlit_hit: 30ms  

shot_groups:
  upperlanes:
    shots: laneLeft, laneMiddle, laneRight
    rotate_left_events: sw_left_flipper
    rotate_right_events: sw_right_flipper
    reset_events: shot_upperLanes_lit_complete

physical_dmd:
  width: 128
  height: 32
  shades: 16
window:
  width: 1024
  height: 256
  title: FAST Pinball Portable Machine
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
virtual_platform_start_active_switches: trough

keyboard:
  z:
    switch: leftFlipper
  /:
    switch: rightFlipper
  s:
    switch: start
  1:
    switch: trough
    toggle: true

  .:
    switch: rightSling

  x:
    switch: leftSling
  up:
    event: action_set_volume
    params:
      change: 0.05
  down:
    event: action_set_volume
    params:
      change: -.05
  l:
    switch: standupMidLeft1

bcp:
  connections:
    local_display:
      host: localhost
      port: 5050
      connection_attempts: 5
      require_connection: true  

displays:
  window:
    height: 256
    width: 1024
  dmd:
    width: 128
    height: 32
    default: true
slides:
  window_slide_1:
  - type: dmd
    width: 1024
    height: 256
    pixel_color: ff0000
    dark_color: 220000
    z: 1
      #- type: Text
      #  font: tall title
      #  text: FAST PINBALL
      #  h_pos: right
      #  v_pos: bottom
      #  y: -10
      #  x: -20
      #  size: 60
      #  antialias: yes
      #  layer: 1
      #  color: ff0000
      #
      #- type: Shape
      #  shape: box
      #  width: 516
      #  height: 132
      #  layer: 2
      #  thickness: 2
      #  v_pos: center
      #  h_pos: center
      #  color: aaaaaa

slide_player:
  machine_reset_phase_3:
    window_slide_1:
      target: window
text_styles:
  default:
    font_name: Quadrit
    font_size: 10
    crop_top: 2
    crop_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    crop_top: 3
    crop_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    crop_top: 2
    crop_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    crop_top: 1
    crop_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    crop_top: 2
    crop_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
show_player:
  mode_attract_started:
    attract_display:
      loops: -1
      speed: 1
    semi_circle_rainbow:
      loops: -1
      speed: 15
    kit:
      loops: -1
      speed: 10
    ball_lock_lane:
      loops: -1
      speed: 8
    top_lanes:
      loops: -1
      speed: 5
    colored_inserts:
      loops: -1
      speed: 4
    rainbow_targets:
      loops: -1
      speed: 30
    top_inserts:
      loops: -1
      speed: 7
    whites:
      loops: -1
      speed: 15        

  mode_attract_stopped:
    attract_display:
      action: stop

    semi_circle_rainbow:
      action: stop
    kit:
      action: stop
    ball_lock_lane:
      action: stop
    top_lanes:
      action: stop
    colored_inserts:
      action: stop
    rainbow_targets:
      action: stop
    top_inserts:
      action: stop
    whites:
      action: stop

