# config_version=3
mode:
    start_events: ball_starting
#    stop_events: ball_ending
    priority: 200
    code: base.Base
    stop_on_ball_end: false

#        ::::::::   ::::::::   ::::::::  :::::::::  ::::::::::: ::::    :::  ::::::::
#      :+:    :+: :+:    :+: :+:    :+: :+:    :+:     :+:     :+:+:   :+: :+:    :+:
#     +:+        +:+        +:+    +:+ +:+    +:+     +:+     :+:+:+  +:+ +:+
#    +#++:++#++ +#+        +#+    +:+ +#++:++#:      +#+     +#+ +:+ +#+ :#:
#          +#+ +#+        +#+    +#+ +#+    +#+     +#+     +#+  +#+#+# +#+   +#+#
#  #+#    #+# #+#    #+# #+#    #+# #+#    #+#     #+#     #+#   #+#+# #+#    #+#
#  ########   ########   ########  ###    ### ########### ###    ####  ########

Scoring:
    eight_ball_top_hit:
        score: 500
    eight_ball_hole_hit:
        score: 500
    slingshot_hit:
        Score: 10
    stripe_hit:
        Score: 500
    solid_hit:
        Score: 500
    rubberBehindDropTarget_hit:
        Score: 210
    inlane_hit:
        Score: 500
    outlane_hit:
        Score: 1000
    balldevice_eightBallHole_ball_enter:
        Score: 500
    midLeftLane_special_lit_hit:
        Score: 1000
    midRightLane_special_lit_hit:
        Score: 1000
    midLeftLane_special_unlit_hit:
        Score: 500
    midRightLane_special_unlit_hit:
        Score: 500
    midLaneRubber:
        Score: 10
    leftstandup_hit:
        Score: 100
    rightstandup_hit:
        Score: 100
    upperOuterRollover_hit:
        Score: 1000
    upperEightBallLane_hit:
        Score: 500
    popBumper3ball_hit:
        Score: 1000
    popBumper5ball_hit:
        Score: 100

#       ::::::::  :::    :::  :::::::: ::::::::::: ::::::::
#     :+:    :+: :+:    :+: :+:    :+:    :+:    :+:    :+:
#    +:+        +:+    +:+ +:+    +:+    +:+    +:+
#   +#++:++#++ +#++:++#++ +#+    +:+    +#+    +#++:++#++
#         +#+ +#+    +#+ +#+    +#+    +#+           +#+
# #+#    #+# #+#    #+# #+#    #+#    #+#    #+#    #+#
# ########  ###    ###  ########     ###     ########

Shots:
    drop1:
        switch: s_drop1
        light: l_ball1
        reset_events: collect_special, mode_base_started
    drop2:
        switch: s_drop2
        light: l_ball2
        reset_events: collect_special, mode_base_started
    drop3:
        switch: s_drop3
        light: l_ball3
        reset_events: collect_special, mode_base_started
    drop4:
        switch: s_drop4
        light: l_ball4
        reset_events: collect_special, mode_base_started
    drop5:
        switch: s_drop5
        light: l_ball5
        reset_events: collect_special, mode_base_started
    drop6:
        switch: s_drop6
        light: l_ball6
        reset_events: collect_special, mode_base_started
    drop7:
        switch: s_drop7
        light: l_ball7
        reset_events: collect_special, mode_base_started
    drop9:
        switch: s_drop9
        light: l_ball9
        reset_events: collect_special, mode_base_started
    drop10:
        switch: s_drop10
        light: l_ball10
        reset_events: collect_special, mode_base_started
    drop11:
        switch: s_drop11
        light: l_ball11
        reset_events: collect_special, mode_base_started
    drop12:
        switch: s_drop12
        light: l_ball12
        reset_events: collect_special, mode_base_started
    drop13:
        switch: s_drop13
        light: l_ball13
        reset_events: collect_special, mode_base_started
    drop14:
        switch: s_drop14
        light: l_ball14
        reset_events: collect_special, mode_base_started
    drop15:
        switch: s_drop15
        light: l_ball15
        reset_events: collect_special, mode_base_started

    eight_ball_top:
        switch: s_topLaneMid
#        light: l_eightBall500 #, l_ball8
#        profile: eightBall
#        reset_events: collect_special, mode_base_started
    eight_ball_hole:
        switch: s_eightBallHoleEject
#        light: l_eightBallHole
#        profile: eightBall
#        reset_events: collect_special, mode_base_started
    slingShot:
        Switch: s_slingL, s_slingR
    solid:
        switch: s_drop1, s_drop2, s_drop3, s_drop4, s_drop5, s_drop6, s_drop7
    stripe:
        switch: s_drop9, s_drop10, s_drop11, s_drop12, s_drop13, s_drop14, s_drop15
    rubberBehindDropTarget:
        Switch: s_behindSolids, s_behindStripes
    inlane:
        Switch: s_leftInlane, s_rightInlane
    outlane:
        Switch: s_leftOutlane, s_rightOutlane
    midLaneRubber:
        Switch: s_midLtRubber, s_midRtRubber
    upperOuterRollover:
        Switch: s_topLaneLeft, s_topLaneRight
#    upperEightBallLane:
#        Switch: s_topLaneMid
#        light: l_eightBall500, l_ball8
    popBumper:
        Switch: s_popBumper
    midRightLane:
        switch: s_midRtLane
        light: l_rtMid1k
        advance_events: mode_base_started
        enable_events: mode_base_started
    midLeftLane:
        switch: s_midLtLane
        light: l_ltMid1k
        enable_events: mode_base_started
    leftStandup:
        switch: s_ltMidStandup
        enable_events: mode_base_started, collect_special
        disable_events: lighting_special
    rightStandup:
        switch: s_rtMidStandup
        enable_events: mode_base_started, collect_special
        disable_events: lighting_special
    specialLeft:
        switch: s_ltMidStandup
        light: l_ltSpecial
        enable_events: lighting_special
        disable_events: mode_base_started, ball_ending, collect_special
    specialRight:
        switch: s_rtMidStandup
        light: l_rtSpecial
        advance_events: lighting_special
        enable_events: lighting_special
        disable_events: mode_base_started, ball_ending, collect_special
        debug: yes

#        ::::::::  :::    :::  :::::::: :::::::::::
#      :+:    :+: :+:    :+: :+:    :+:    :+:
#     +:+        +:+    +:+ +:+    +:+    +:+
#    +#++:++#++ +#++:++#++ +#+    +:+    +#+
#          +#+ +#+    +#+ +#+    +#+    +#+
#  #+#    #+# #+#    #+# #+#    #+#    #+#
#  ########  ###    ###  ########     ###

#        ::::::::  :::::::::   ::::::::  :::    ::: :::::::::   ::::::::
#      :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+:
#     +:+        +:+    +:+ +:+    +:+ +:+    +:+ +:+    +:+ +:+
#    :#:        +#++:++#:  +#+    +:+ +#+    +:+ +#++:++#+  +#++:++#++
#   +#+   +#+# +#+    +#+ +#+    +#+ +#+    +#+ +#+               +#+
#  #+#    #+# #+#    #+# #+#    #+# #+#    #+# #+#        #+#    #+#
#  ########  ###    ###  ########   ########  ###         ########

Shot_Groups:
    middleLanes:
        shots: midRightLane, midLeftLane
        rotate_left_events: sw_sling
        #reset_events: mode_base_started
        enable_events: mode_base_started
        profile: special

    specialStandups:
        shots: specialLeft, specialRight
        rotate_left_events: sw_sling
        reset_events: collect_special, mode_base_started
        enable_events: lighting_special
        disable_events: mode_base_started, collect_special, ball_ending
        profile: special
        #debug: yes


#        :::        ::::::::   :::::::: ::::::::::: ::::::::
#       :+:       :+:    :+: :+:    :+:    :+:    :+:    :+:
#      +:+       +:+    +:+ +:+           +:+    +:+
#     +#+       +#+    +:+ :#:           +#+    +#+
#    +#+       +#+    +#+ +#+   +#+#    +#+    +#+
#   #+#       #+#    #+# #+#    #+#    #+#    #+#    #+#
#  ########## ########   ######## ########### ########

#        :::::::::  :::        ::::::::   ::::::::  :::    ::: ::::::::
#       :+:    :+: :+:       :+:    :+: :+:    :+: :+:   :+: :+:    :+:
#      +:+    +:+ +:+       +:+    +:+ +:+        +:+  +:+  +:+
#     +#++:++#+  +#+       +#+    +:+ +#+        +#++:++   +#++:++#++
#    +#+    +#+ +#+       +#+    +#+ +#+        +#+  +#+         +#+
#   #+#    #+# #+#       #+#    #+# #+#    #+# #+#   #+# #+#    #+#
#  #########  ########## ########   ########  ###    ### ########

Logic_Blocks:
    Accruals:
        light_special:
            events:
                - sw_eightball
                - solids_down, solids_down
            events_when_complete: lighting_special, action_target_specialRight_light
            enable_events: ball_started
            disable_events: ball_ended, lighting_special
            reset_events: ball_ended, lighting_special

        collect_special:
            events:
                - specialStandups_special_lit_hit
            events_when_complete: collect_special
            enable_events: lighting_special
            disable_events: collect_special, mode_base_started
            reset_events: collect_special, mode_base_started

        lightEightBall:
            events:
                - sw_eightball
            events_when_complete:
                - light_ball8, unlight_shot_lights
            enable_events: ball_started
            disable_events: ball_ended
            reset_events: ball_ended

        unlightEightBall:
            events:
                - collect_special, ball_started
            events_when_complete:
                - unlight_ball8, light_shot_lights
            enable_events: ball_started
            disable_events: ball_ended
            reset_events: ball_ended

        openDiverter:
            events:
                - s_eightBallHoleEject_active
            events_when_complete:
                open_diverter
            enable_events: ball_started
            disable_events: ball_ended
            reset_events: ball_ended

light_player:
    light_ball8:
        lights: l_ball8
        script: "on"
    unlight_shot_lights:
        lights: l_eightBall500, l_eightBallHole
        script: "off"
    unlight_ball8:
        lights: l_ball8
        script: "off"
    light_shot_lights:
        lights: l_eightBall500, l_eightBallHole
        script: "on"
