# config_version=4
mode:
  start_events: ball_starting
#    stop_events: ball_ending
  priority: 200
#  code: base.Base
  stop_on_ball_end: false

#        ::::::::   ::::::::   ::::::::  :::::::::  ::::::::::: ::::    :::  ::::::::
#      :+:    :+: :+:    :+: :+:    :+: :+:    :+:     :+:     :+:+:   :+: :+:    :+:
#     +:+        +:+        +:+    +:+ +:+    +:+     +:+     :+:+:+  +:+ +:+
#    +#++:++#++ +#+        +#+    +:+ +#++:++#:      +#+     +#+ +:+ +#+ :#:
#          +#+ +#+        +#+    +#+ +#+    +#+     +#+     +#+  +#+#+# +#+   +#+#
#  #+#    #+# #+#    #+# #+#    #+# #+#    #+#     #+#     #+#   #+#+# #+#    #+#
#  ########   ########   ########  ###    ### ########### ###    ####  ########

scoring:
  eight_ball_top_hit:
    score: 500
  eight_ball_hole_hit:
    score: 500
  slingshot_hit:
    score: 10
  stripe_hit:
    score: 500
  solid_hit:
    score: 500
  rubberbehinddroptarget_hit:
    score: 210
  inlane_hit:
    score: 500
  outlane_hit:
    score: 1000
  balldevice_eightballhole_ball_enter:
    score: 500
  midleftlane_special_lit_hit:
    score: 1000
  midrightlane_special_lit_hit:
    score: 1000
  midleftlane_special_unlit_hit:
    score: 500
  midrightlane_special_unlit_hit:
    score: 500
  midlanerubber:
    score: 10
  leftstandup_hit:
    score: 100
  rightstandup_hit:
    score: 100
  upperouterrollover_hit:
    score: 1000
  uppereightballlane_hit:
    score: 500
  popbumper3ball_hit:
    score: 1000
  popbumper5ball_hit:
    score: 100 

#       ::::::::  :::    :::  :::::::: ::::::::::: ::::::::
#     :+:    :+: :+:    :+: :+:    :+:    :+:    :+:    :+:
#    +:+        +:+    +:+ +:+    +:+    +:+    +:+
#   +#++:++#++ +#++:++#++ +#+    +:+    +#+    +#++:++#++
#         +#+ +#+    +#+ +#+    +#+    +#+           +#+
# #+#    #+# #+#    #+# #+#    #+#    #+#    #+#    #+#
# ########  ###    ###  ########     ###     ########

shots:
  drop1:
    switch: s_drop1
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball1
  drop2:
    switch: s_drop2
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball2
  drop3:
    switch: s_drop3
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball3
  drop4:
    switch: s_drop4
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball4
  drop5:
    switch: s_drop5
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball5
  drop6:
    switch: s_drop6
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball6
  drop7:
    switch: s_drop7
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball7
  drop9:
    switch: s_drop9
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball9
  drop10:
    switch: s_drop10
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball10
  drop11:
    switch: s_drop11
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball11
  drop12:
    switch: s_drop12
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball12
  drop13:
    switch: s_drop13
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball13
  drop14:
    switch: s_drop14
    reset_events: collect_special, mode_base_started
    show_tokens:
      light: l_ball14
  drop15:
    switch: s_drop15
    reset_events: collect_special, mode_base_started

    show_tokens:
      light: l_ball15
  eight_ball_top:
    switch: s_topLaneMid
#        light: l_eightBall500 #, l_ball8
#        profile: eightBall
#        reset_events: collect_special, mode_base_started
  eight_ball_hole:
    switch: s_eightBallHoleEject
#        light: l_eightBallHole
#        profile: eightBall
#        reset_events: collect_special, mode_base_started
  slingshot:
    switch: s_slingL, s_slingR
  solid:
    switch: s_drop1, s_drop2, s_drop3, s_drop4, s_drop5, s_drop6, s_drop7
  stripe:
    switch: s_drop9, s_drop10, s_drop11, s_drop12, s_drop13, s_drop14, s_drop15
  rubberbehinddroptarget:
    switch: s_behindSolids, s_behindStripes
  inlane:
    switch: s_leftInlane, s_rightInlane
  outlane:
    switch: s_leftOutlane, s_rightOutlane
  midlanerubber:
    switch: s_midLtRubber, s_midRtRubber
  upperouterrollover:
    switch: s_topLaneLeft, s_topLaneRight
#    upperEightBallLane:
#        Switch: s_topLaneMid
#        light: l_eightBall500, l_ball8
  popbumper:
    switch: s_popBumper
  midrightlane:
    switch: s_midRtLane
    advance_events: mode_base_started
    enable_events: mode_base_started
    show_tokens:
      light: l_rtMid1k
  midleftlane:
    switch: s_midLtLane
    enable_events: mode_base_started
    show_tokens:
      light: l_ltMid1k
  leftstandup:
    switch: s_ltMidStandup
    enable_events: mode_base_started, collect_special
    disable_events: lighting_special
  rightstandup:
    switch: s_rtMidStandup
    enable_events: mode_base_started, collect_special
    disable_events: lighting_special
  specialleft:
    switch: s_ltMidStandup
    enable_events: lighting_special
    disable_events: mode_base_started, ball_ending, collect_special
    show_tokens:
      light: l_ltSpecial
  specialright:
    switch: s_rtMidStandup
    advance_events: lighting_special
    enable_events: lighting_special
    disable_events: mode_base_started, ball_ending, collect_special
    debug: true

    show_tokens:
      light: l_rtSpecial
#        ::::::::  :::    :::  :::::::: :::::::::::
#      :+:    :+: :+:    :+: :+:    :+:    :+:
#     +:+        +:+    +:+ +:+    +:+    +:+
#    +#++:++#++ +#++:++#++ +#+    +:+    +#+
#          +#+ +#+    +#+ +#+    +#+    +#+
#  #+#    #+# #+#    #+# #+#    #+#    #+#
#  ########  ###    ###  ########     ###

#        ::::::::  :::::::::   ::::::::  :::    ::: :::::::::   ::::::::
#      :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+:
#     +:+        +:+    +:+ +:+    +:+ +:+    +:+ +:+    +:+ +:+
#    :#:        +#++:++#:  +#+    +:+ +#+    +:+ +#++:++#+  +#++:++#++
#   +#+   +#+# +#+    +#+ +#+    +#+ +#+    +#+ +#+               +#+
#  #+#    #+# #+#    #+# #+#    #+# #+#    #+# #+#        #+#    #+#
#  ########  ###    ###  ########   ########  ###         ########

shot_groups:
  middlelanes:
    shots: midRightLane, midLeftLane
    rotate_left_events: sw_sling
        #reset_events: mode_base_started
    enable_events: mode_base_started
    profile: special

  specialstandups:
    shots: specialLeft, specialRight
    rotate_left_events: sw_sling
    reset_events: collect_special, mode_base_started
    enable_events: lighting_special
    disable_events: mode_base_started, collect_special, ball_ending
    profile: special
        #debug: yes


#        :::        ::::::::   :::::::: ::::::::::: ::::::::
#       :+:       :+:    :+: :+:    :+:    :+:    :+:    :+:
#      +:+       +:+    +:+ +:+           +:+    +:+
#     +#+       +#+    +:+ :#:           +#+    +#+
#    +#+       +#+    +#+ +#+   +#+#    +#+    +#+
#   #+#       #+#    #+# #+#    #+#    #+#    #+#    #+#
#  ########## ########   ######## ########### ########

#        :::::::::  :::        ::::::::   ::::::::  :::    ::: ::::::::
#       :+:    :+: :+:       :+:    :+: :+:    :+: :+:   :+: :+:    :+:
#      +:+    +:+ +:+       +:+    +:+ +:+        +:+  +:+  +:+
#     +#++:++#+  +#+       +#+    +:+ +#+        +#++:++   +#++:++#++
#    +#+    +#+ +#+       +#+    +#+ +#+        +#+  +#+         +#+
#   #+#    #+# #+#       #+#    #+# #+#    #+# #+#   #+# #+#    #+#
#  #########  ########## ########   ########  ###    ### ########

logic_blocks:
  accruals:
    light_special:
      events:
      - sw_eightball
      - solids_down, solids_down
      events_when_complete: lighting_special, action_target_specialRight_light
      enable_events: ball_started
      disable_events: ball_ended, lighting_special
      reset_events: ball_ended, lighting_special

    collect_special:
      events:
      - specialStandups_special_lit_hit
      events_when_complete: collect_special
      enable_events: lighting_special
      disable_events: collect_special, mode_base_started
      reset_events: collect_special, mode_base_started

    lighteightball:
      events:
      - sw_eightball
      events_when_complete:
      - light_ball8, unlight_shot_lights
      enable_events: ball_started
      disable_events: ball_ended
      reset_events: ball_ended

    unlighteightball:
      events:
      - collect_special, ball_started
      events_when_complete:
      - unlight_ball8, light_shot_lights
      enable_events: ball_started
      disable_events: ball_ended
      reset_events: ball_ended

    opendiverter:
      events:
      - s_eightBallHoleEject_active
      events_when_complete: open_diverter
      enable_events: ball_started
      disable_events: ball_ended
      reset_events: ball_ended

show_player:
  light_ball8:
    on:
      show_tokens:
        lights: l_ball8
  unlight_shot_lights:
    off:
      show_tokens:
        lights: l_eightBall500, l_eightBallHole
  unlight_ball8:
    off:
      show_tokens:
        lights: l_ball8
  light_shot_lights:
    on:
      show_tokens:
        lights: l_eightBall500, l_eightBallHole
