#config_version=6

animations:
  shot_off:
    - property: opacity
      value: 0.5
      duration: 0
  shot_on:
    - property: opacity
      value: 1.0
      duration: 0
  shot_flashing:
    - property: opacity
      value: 1.0
      duration: 250ms
    - property: opacity
      value: 0.5
      duration: 250ms
      repeat: true

widget_player:
  mode_sequential_drops_started:
    sequential_drops_widget:
      action: add
      slide: base_slide

widgets:
  sequential_drops_widget:
    - type: ellipse
      opacity: 1.0
      width: 20
      height: 20
      y: 20
      x: 230
      animations:
        add_to_slide: shot_flashing
        player_shot_drop_1{value==0}: shot_off
        player_shot_drop_1{value==1}: shot_flashing
        player_shot_drop_1{value==2}: shot_on
    - type: ellipse
      opacity: 0.5
      width: 20
      height: 20
      y: 20
      x: 290
      animations:
        player_shot_drop_2{value==0}: shot_off
        player_shot_drop_2{value==1}: shot_flashing
        player_shot_drop_2{value==2}: shot_on
    - type: ellipse
      opacity: 0.5
      width: 20
      height: 20
      y: 20
      x: 350
      animations:
        player_shot_drop_3{value==0}: shot_off
        player_shot_drop_3{value==1}: shot_flashing
        player_shot_drop_3{value==2}: shot_on
    - type: ellipse
      opacity: 0.5
      width: 20
      height: 20
      y: 20
      x: 410
      animations:
        player_shot_drop_4{value==0}: shot_off
        player_shot_drop_4{value==1}: shot_flashing
        player_shot_drop_4{value==2}: shot_on
